classdef UICheckbox < ndi.gui.component.internal.uie.UIElement & ...
                      ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                      ndi.gui.component.internal.uie.mixin.UITextComponent & ...
                      ndi.gui.component.internal.uie.mixin.UIInteractiveComponent & ...
                      ndi.gui.component.internal.uie.mixin.UIValue & ...
                      ndi.gui.component.internal.uie.mixin.UIValueChangedFcn & ...
                      ndi.gui.component.internal.uie.mixin.UIText
    % UICHECKBOX Describes a checkbox UI component.
    %
    % This class uses multiple inheritance to compose all necessary features
    % from the elemental, visual, text, interactive, and value mixin classes.

end