classdef UIEditField < ndi.gui.component.internal.uie.UIElement & ...
                       ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                       ndi.gui.component.internal.uie.mixin.UITextComponent & ...
                       ndi.gui.component.internal.uie.mixin.UIInteractiveComponent & ...
                       ndi.gui.component.internal.uie.mixin.UIValue & ...
                       ndi.gui.component.internal.uie.mixin.UIValueChangedFcn & ...
                       ndi.gui.component.internal.uie.mixin.UIValueChangingFcn &...
                       ndi.gui.component.internal.uie.mixin.UIHorizontalAlignment &...
                       ndi.gui.component.internal.uie.mixin.UIPlaceholder
    % UIEDITFIELD Describes an editable, single-line text field.

end