classdef UILabel < ndi.gui.component.internal.uie.UIElement & ...
                   ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                   ndi.gui.component.internal.uie.mixin.UITextComponent &...
                   ndi.gui.component.internal.uie.mixin.UIHorizontalAlignment & ...
                   ndi.gui.component.internal.uie.mixin.UIVerticalAlignment & ...
                   ndi.gui.component.internal.uie.mixin.UIText

    % UILABEL Describes a static text label UI component.

end