classdef UIPanel < ndi.gui.component.internal.uie.mixin.UIContainer & ...
                   ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                   ndi.gui.component.internal.uie.mixin.UITextComponent & ...
                   ndi.gui.component.internal.uie.mixin.UITitle & ...
                   ndi.gui.component.internal.uie.mixin.UIBorderType & ...
                   ndi.gui.component.internal.uie.UIElement

    % UIPANEL Describes a panel container component.
    
end