classdef UITab < ndi.gui.component.internal.uie.mixin.UIContainer & ...
                 ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                 ndi.gui.component.internal.uie.mixin.UITextComponent & ...
                 ndi.gui.component.internal.uie.mixin.UITitle & ...
                 ndi.gui.component.internal.uie.UIElement 
    % UITAB Describes a single tab within a tab group.
    
    properties
    end

end