classdef UITab < ndi.gui.component.internal.uie.UIContainer & ...
                 ndi.gui.component.internal.uie.UIVisualComponent & ...
                 ndi.gui.component.internal.uie.UITextComponent & ...
                 ndi.gui.component.internal.uie.UITitle & ...
                 ndi.gui.component.internal.uie.UIElement 
    % UITAB Describes a single tab within a tab group.
    
    properties
    end

end