classdef UITextArea < ndi.gui.component.internal.uie.UIElement & ...
                      ndi.gui.component.internal.uie.mixin.UIVisualComponent & ...
                      ndi.gui.component.internal.uie.mixin.UITextComponent & ...
                      ndi.gui.component.internal.uie.mixin.UIInteractiveComponent & ...
                      ndi.gui.component.internal.uie.mixin.UIValue & ...
                      ndi.gui.component.internal.uie.mixin.UIValueChangedFcn & ...
                      ndi.gui.component.internal.uie.mixin.UIValueChangingFcn & ...
                      ndi.gui.component.internal.uie.mixin.UIPlaceholder & ...
                      ndi.gui.component.internal.uie.mixin.UIWordWrap
    % UITEXTAREA Describes an editable, multi-line text area.
    
    methods
        function obj = UITextArea()
            % Override the default WordWrap from UITextComponent for this class
            obj.WordWrap = 'on';
        end
    end
    
end