exportDir = fullfile(ndi.common.PathConstants.CommonFolder, 'daq_systems', 'vhlab');
if ~isfolder(exportDir); mkdir(exportDir); end

% Export "vhintan" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhintan';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.intan', ...
    'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
    'FileParameters', {'reference.txt', ...
    '.*\.rhd\>', ...
    'vhintan_channelgrouping.txt', ...
    'vhintan_intan2spike2time.txt'}, ...
    'EpochProbeMapFileParameters', 'vhintan_channelgrouping.txt', ...
    'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

% Export "vhspike2" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhspike2';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.cedspike2', ...
    'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
    'FileParameters', {'reference.txt', ...
    '.*\.smr\>', ...
    'vhspike2_channelgrouping.txt'}, ...
    'EpochProbeMapFileParameters', 'vhspike2_channelgrouping.txt', ...
    'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

daqSystemConfig2 = ndi.setup.DaqSystemConfiguration.fromConfigFile(...
    fullfile(exportDir, [daqSystemName, '.json']));

% Export "vhvis_spike2" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhvis_spike2';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.setup.daq.reader.mfdaq.stimulus.vhlabvisspike2', ...
    'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
    'MetadataReaderClass', 'ndi.daq.metadatareader.NewStimStims', ...
    'FileParameters', {'reference.txt', ...
    'stimtimes.txt', ...
    'verticalblanking.txt', ...
    'stims.mat', ...
    'spike2data.smr'}, ...
    'EpochProbeMapFileParameters', 'stimtimes.txt', ...
    'MetadataReaderFileParameters', 'stims.mat', ...
    'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

% Export "vhneuropixels" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhneuropixels';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.ndr', ...
    'DaqReaderFileParameters', 'neuropixelsGLX', ...
    'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
    'FileParameters', {'reference.txt', ...
    '#_g0_imec0.ap.bin', ...
    '#_g0_imec0.ap.meta'}, ...
    'HasEpochDirectories', false);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

% Export "vhneuropixelsGLX" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% Mirrors the kjnielsenlab nielsen_neuropixelsGLX configuration so vhlab
% SpikeGLX / Neuropixels GLX sessions can be read with the same file layout
% (one epoch per *_g0 directory).
daqSystemName = 'vhneuropixelsGLX';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.ndr', ...
    'DaqReaderFileParameters', 'neuropixelsGLX', ...
    'EpochProbeMapClass', 'ndi.epoch.epochprobemap_daqsystem', ...
    'FileParameters', {'#.imec0.ap\.bin\>', ...
    '#.imec0.ap\.meta\>', ...
    '#.nidq\.meta\>', ...
    'epochprobemap.txt'}, ...
    'EpochProbeMapFileParameters', 'epochprobemap.txt', ...
    'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

% Export "vhajbpod_np" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% The vhajbpod_np stimulator is the AJBPod analog to vhtaste_bpod but with
% stimulus triggers acquired on the SpikeGLX NI-DAQ digital input 1
% ('di1') rather than on an Intan board. The _stimulus_triggers_log.tsv
% and *_summary_log.json files live in an Epoch_Set_X subdirectory inside
% each Epoch*_g0 epoch directory, so a custom file navigator is used to
% collect files from both the epoch directory and its subdirectories.
daqSystemName = 'vhajbpod_np';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.setup.daq.reader.mfdaq.stimulus.VHAudreyBPod', ...
    'MetadataReaderClass', 'ndi.daq.metadatareader.VHAudreyBPod', ...
    'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
    'FileNavigatorClass', 'ndi.setup.file.navigator.vhlab_np_epochdir', ...
    'FileParameters', {'.*\.nidq\.bin\>', ...
    '.*\.nidq\.meta\>', ...
    '.*\.imec0\.ap\.meta\>', ...
    '.*_stimulus_triggers_log\.tsv\>', ...
    '.*_summary_log\.json\>'}, ...
    'MetadataReaderFileParameters', '(.*)\.json', ...
    'EpochProbeMapFileParameters', '.*_stimulus_triggers_log\.tsv\>', ...
    'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))
