function testToolbox(varargin)
    installMatBox()
    projectRootDir = nditools.projectdir();
    matbox.tasks.testToolbox(projectRootDir, ...
        "CodeFolderName", "", ...
        "ToolsFolderName", "", ...
        varargin{:})
end
