function testToolbox(varargin)
    installMatBox()
    ndi_install()
    projectRootDir = nditools.projectdir();
    matbox.tasks.testToolbox(projectRootDir, ...
        "SourceFolderName", "", ...
        "ToolsFolderName", "", ...
        varargin{:})
end
