function [are_identical, diff_output] = getHexDiffFromFileObj(file_obj1, file_obj2, options)
% GETHEXDIFFFROMFILEOBJ - Compare two file objects chunk by chunk for equality.
%
%   [ARE_IDENTICAL, DIFF_OUTPUT] = ndi.util.getHexDiffFromFileObj(FILE_OBJ1, FILE_OBJ2, ...)
%
%   Compares two did.file.fileobj file objects (structs with a field 'fid' which is a file identifier)
%   in a memory-efficient manner by reading them in chunks.
%
%   Outputs:
%   ARE_IDENTICAL - A boolean that is true if the files are identical, and false otherwise.
%   DIFF_OUTPUT   - A string that is empty if the files are identical. If they are
%                   different, it contains a hex diff of the first mismatched chunk,
%                   generated by `ndi.util.hexDiffBytes`.
%
%   This function also takes name/value pairs that modify its behavior.
%   'chunkSize' (default 1048576)  - The size of chunks (in bytes) to read from the files for comparison.
%
    arguments
        file_obj1 (1,1) did.file.fileobj
        file_obj2 (1,1) did.file.fileobj
        options.chunkSize (1,1) {mustBeInteger, mustBePositive} = 1024*1024 % 1MB default
    end

    are_identical = true;
    diff_output = '';

    % Rewind files to the beginning
    fseek(file_obj1.fid, 0, 'bof');
    fseek(file_obj2.fid, 0, 'bof');

    cleanupObj1 = onCleanup(@() fseek(file_obj1.fid, 0, 'bof')); % ensure rewind after we are done
    cleanupObj2 = onCleanup(@() fseek(file_obj2.fid, 0, 'bof')); % ensure rewind after we are done

    % --- 1. First, check the file sizes ---
    fseek(file_obj1.fid, 0, 'eof');
    size1 = ftell(file_obj1.fid);
    fseek(file_obj2.fid, 0, 'eof');
    size2 = ftell(file_obj2.fid);

    % Rewind again for reading
    fseek(file_obj1.fid, 0, 'bof');
    fseek(file_obj2.fid, 0, 'bof');

    if size1 ~= size2
        are_identical = false;
        diff_output = sprintf('Files have different sizes (%d bytes vs %d bytes).', size1, size2);

        % Also provide a hex diff of the beginning of the files for context
        data1 = fread(file_obj1.fid, options.chunkSize, '*uint8');
        data2 = fread(file_obj2.fid, options.chunkSize, '*uint8');

        % Only add the hexdiff if the content actually differs in the first chunk
        if ~isequal(data1, data2)
            diff_output = [diff_output char(10) 'Hexdiff of the start of the files:' char(10) ndi.util.hexDiffBytes(data1, data2)];
        end
        return;
    end

    % --- 2. If sizes are identical, compare content chunk by chunk ---
    offset = 0;
    while ~feof(file_obj1.fid)
        data1 = fread(file_obj1.fid, options.chunkSize, '*uint8');
        data2 = fread(file_obj2.fid, options.chunkSize, '*uint8');

        if ~isequal(data1, data2)
            are_identical = false;
            diff_output = ndi.util.hexDiffBytes(data1, data2, 'StartOffset', offset);
            return;
        end
        offset = offset + numel(data1); % Use actual bytes read for offset
    end
end
