function [are_identical, diff_output] = getHexDiffFromFileObj(file_obj1, file_obj2, options)
% GETHEXDIFFFROMFILEOBJ - Compare two file objects chunk by chunk for equality.
%
%   [ARE_IDENTICAL, DIFF_OUTPUT] = ndi.util.getHexDiffFromFileObj(FILE_OBJ1, FILE_OBJ2, ...)
%
%   Compares two file objects (structs with a field 'fid' which is a file identifier)
%   in a memory-efficient manner by reading them in chunks.
%
%   Outputs:
%   ARE_IDENTICAL - A boolean that is true if the files are identical, and false otherwise.
%   DIFF_OUTPUT   - A string that is empty if the files are identical. If they are
%                   different, it contains a hex diff of the first mismatched chunk,
%                   generated by `vlt.string.hexdiff`.
%
%   This function also takes name/value pairs that modify its behavior.
%   'chunkSize' (default 1048576)  - The size of chunks (in bytes) to read from the files for comparison.
%
    arguments
        file_obj1 (1,1) struct
        file_obj2 (1,1) struct
        options.chunkSize (1,1) {mustBeInteger, mustBePositive} = 1024*1024 % 1MB default
    end

    are_identical = true;
    diff_output = '';

    % Rewind files to the beginning for a full comparison
    fseek(file_obj1.fid, 0, 'bof');
    fseek(file_obj2.fid, 0, 'bof');

    cleanupObj1 = onCleanup(@() fseek(file_obj1.fid, 0, 'bof')); % rewind after we are done
    cleanupObj2 = onCleanup(@() fseek(file_obj2.fid, 0, 'bof')); % rewind after we are done

    while ~feof(file_obj1.fid) && ~feof(file_obj2.fid)
        data1 = fread(file_obj1.fid, options.chunkSize, '*uint8');
        data2 = fread(file_obj2.fid, options.chunkSize, '*uint8');

        if ~isequal(data1, data2)
            are_identical = false;
            % Assuming vlt.string.hexdiff exists and creates a string report
            diff_output = vlt.string.hexdiff(data1, data2);
            return;
        end
    end

    % After the loop, check if one file has more data than the other
    if feof(file_obj1.fid) ~= feof(file_obj2.fid)
        are_identical = false;
        diff_output = 'Files have different sizes. Comparison stopped at end of shorter file.';
        % Optionally, provide a diff of the remaining content of the longer file
        if ~feof(file_obj1.fid)
            data1 = fread(file_obj1.fid, options.chunkSize, '*uint8'); % Read one more chunk
            diff_output = [diff_output char(10) 'Hexdiff of remaining content in first file:' char(10) vlt.string.hexdiff(data1, uint8([]))];
        else % file 2 is longer
            data2 = fread(file_obj2.fid, options.chunkSize, '*uint8'); % Read one more chunk
            diff_output = [diff_output char(10) 'Hexdiff of remaining content in second file:' char(10) vlt.string.hexdiff(uint8([]), data2)];
        end
    end

end
