classdef VHAudreyBPod < ndi.daq.metadatareader
    % NDI.DAQ.METADATAREADER.VHAUDREYBPOD - Metadata reader for VHAudreyBPod JSON files
    %
    % This class reads metadata from JSON files generated by the VHAudreyBPod system.
    % It parses the parameters for stimulus presentation.

    methods
        function obj = VHAudreyBPod(varargin)
            % VHAUDREYBPOD - Create a new VHAudreyBPod metadata reader object
            %
            % OBJ = NDI.DAQ.METADATAREADER.VHAUDREYBPOD(VARARGIN)
            %
            % Creates a new VHAudreyBPod object. Arguments are passed to the superclass constructor.
            obj = obj@ndi.daq.metadatareader(varargin{:});
        end

        function parameters = readmetadatafromfile(obj, file)
            % READMETADATAFROMFILE - Read metadata from a JSON file
            %
            % PARAMETERS = READMETADATAFROMFILE(OBJ, FILE)
            %
            % Reads the specified JSON file and returns a cell array of stimulus parameters.

            % Read the file content
            fid = fopen(file, 'r');
            if fid == -1
                error(['Could not open file ' file]);
            end
            raw_content = fread(fid, '*char')';
            fclose(fid);

            % Parse JSON
            json_struct = jsondecode(raw_content);

            % Process the structure using the static method
            parameters = ndi.daq.metadatareader.VHAudreyBPod.readAudreyBPodJson(json_struct);
        end
    end

    methods (Static)
        function parameters = readAudreyBPodJson(S)
            % READAUDREYBPODJSON - Convert VHAudreyBPod structure to parameter cell array
            %
            % PARAMETERS = READAUDREYBPODJSON(S)
            %
            % Inputs:
            %   S - A structure containing VHAudreyBPod parameters (e.g., from a JSON file)
            %       Expected fields include:
            %       - DelayB4NextStim, WashDuration, InterStimTime, NumTrials, WaterSolenoidNum
            %       - Stim[1-6]OpenDuration
            %       - Sol[1-6], Sol[1-6]Valve, Sol[1-6]_Tastant, Sol[1-6]_Concentration
            %
            % Outputs:
            %   PARAMETERS - A 1x7 cell array of structures describing each stimulus.
            %                Entries 1-6 correspond to Solenoids 1-6.
            %                Entry 7 corresponds to the Wash/Water stimulus.

            arguments
                S (1,1) struct
            end

            parameters = cell(1, 7);

            % Common parameters
            DelayBeforeNextStim = S.DelayB4NextStim;
            WashDuration = S.WashDuration;
            InterStimulusTime = S.InterStimTime;

            % Process entries 1 through 6
            for k = 1:6
                entry = struct();
                entry.stimid = k;

                % Dynamic field access
                sol_k = ['Sol' num2str(k)];
                entry.isUsed = S.(sol_k);

                sol_valve_k = ['Sol' num2str(k) 'Valve'];
                entry.solenoidValve = S.(sol_valve_k);

                sol_tastant_k = ['Sol' num2str(k) '_Tastant'];
                entry.tastant = S.(sol_tastant_k);

                stim_dur_k = ['Stim' num2str(k) 'OpenDuration'];
                entry.solenoidOpenDuration = S.(stim_dur_k);

                entry.DelayBeforeNextStim = DelayBeforeNextStim;
                entry.WashDuration = WashDuration;
                entry.InterStimulusTime = InterStimulusTime;
                entry.isblank = double(strcmpi(entry.tastant, 'water'));

                parameters{k} = entry;
            end

            % Process entry 7 (Wash/Water)
            entry7 = struct();
            entry7.stimid = 7;
            entry7.isUsed = 1; % Always used
            entry7.solenoidValve = S.WaterSolenoidNum;
            entry7.tastant = 'Water';
            entry7.solenoidOpenDuration = WashDuration;
            entry7.DelayBeforeNextStim = DelayBeforeNextStim;
            entry7.WashDuration = WashDuration;
            entry7.InterStimulusTime = InterStimulusTime;
            entry7.isblank = 0;

            parameters{7} = entry7;
        end
    end
end
