classdef document < did.document
    %NDI.DOCUMENT - NDI_database storage item, general purpose data and parameter storage
    % The ndi.document datatype for storing results in the ndi.database
    %
    % The ndi.document object is the primary method for storing data in the NDI database.
    % Each document has a specific schema type (e.g., 'base', 'session', 'stimulus').
    %
    % Important Rules for Creating Documents:
    % 1. Do not provide 'base.id' or 'base.datestamp' manually. These are automatically
    %    generated by the system to ensure uniqueness and accuracy.
    % 2. Use the 'document_properties' structure to create new versions or copies of
    %    documents.
    % 3. When specifying 'DOCUMENT_TYPE', use the name of the NDI document schema type
    %    without the '.json' extension (e.g., use 'stimulus' not 'stimulus.json').
    %

    % document_properties is inherited from did.document. It is deliberately
    % NOT redeclared here: MATLAB rejects redefining an inherited property,
    % and two copies of the same state is the drift this subclassing removes.

    methods
        function ndi_document_obj = document(document_type, varargin)
            % ndi.document - create a new ndi.database object
            %
            % NDI_DOCUMENT_OBJ = ndi.document(DOCUMENT_TYPE, 'PARAM1', VALUE1, ...)
            %   or
            % NDI_DOCUMENT_OBJ = ndi.document(MATLAB_STRUCT)
            %
            % Creates a new NDI document.
            %
            % Inputs:
            %   DOCUMENT_TYPE - The schema type of the document (e.g., 'base', 'stimulus').
            %                   Do NOT include the '.json' extension.
            %   'PARAM1', VALUE1, ... - Name/Value pairs for setting document properties.
            %                           Properties should be fully qualified (e.g., 'base.name').
            %
            %   Alternatively, a MATLAB_STRUCT containing the document properties can be passed.
            %
            % Notes:
            %   - The 'base.id' and 'base.datestamp' fields are automatically generated and should
            %     not be provided as arguments unless one is recreating a document from an existing
            %     structure (e.g., loading from disk).
            %   - To create a modified copy of a document, pass the 'document_properties' of the
            %     existing document as the first argument, and then modify the properties of the
            %     resulting object.
            %
            if nargin<1
                document_type = 'base';
            end

            madeFromDefinition = false;
            if isstruct(document_type)
                document_properties = document_type;
            elseif isa(document_type,'did.document')
                document_properties = document_type.document_properties; % directly compatible
            else  % create blank from definitions
                madeFromDefinition = true;
                document_properties = ndi.document.readblankdefinition(document_type);
                ndiido = ndi.ido();
                document_properties.base.id = ndiido.id();
                document_properties.base.datestamp = ndi.fun.timestamp();

                if numel(varargin)==1 % see if user put it all as one cell array
                    if iscell(varargin{1})
                        varargin = varargin{1};
                    end
                end
                if mod(numel(varargin),2)~=0
                    error('Variable inputs must be name/value pairs'.');
                end

                for i=1:2:numel(varargin) % assign variable arguments
                    try
                        document_properties = ndi.util.assignPropertyPath( ...
                            document_properties, varargin{i}, varargin{i+1});
                    catch
                        error(['Could not assign document_properties.' varargin{i} '.']);
                    end
                end
            end

            % Hand the resolved properties to did.document's struct path.
            % That path is what makes subclassing possible: did.document's
            % constructor calls did.document.readblankdefinition with the
            % class name written out, and MATLAB does not dispatch an
            % explicitly qualified static call virtually, so an inherited
            % constructor would resolve $NDIDOCUMENTPATH through DID's
            % resolver. Resolving here first and passing the struct
            % sidesteps that.
            ndi_document_obj@did.document(document_properties);

            % did.document seeds files.file_info when it builds a blank
            % document from a definition, and its add_file assumes the field
            % exists; ndi.document never called reset_file_info and created
            % the field lazily instead. The struct path skips the seeding, so
            % do it here to meet did.document's contract.
            %
            % This now runs did.document's reset_file_info rather than a copy
            % of it, so when DID's grows the series_info seeding of
            % VH-Lab/DID-matlab#178, ndi.document gets it without a change
            % here. Against DID main the two are the same function.
            if madeFromDefinition
                ndi_document_obj = ndi_document_obj.reset_file_info();
            end

        end % ndi.document() creator

        function ndi_document_obj = set_session_id(ndi_document_obj, session_id)
            % SET_SESSION_ID - set the session id for an ndi.document object
            %
            % NDI_DOCUMENT_OBJ = SET_SESSION_ID(NDI_DOCUMENT_OBJ, SESSION_ID)
            %
            % Sets the document_properties.base.session_id field to the value indicated.
            %
            ndi_document_obj.document_properties.base.session_id = session_id;
        end % set_session_id

        function t = to_table(ndi_document_obj)
            % TO_TABLE - convert an ndi.document to a table
            %
            % T = TO_TABLE(NDI_DOCUMENT_OBJ)
            %
            % Convert an ndi.document to a Matlab table.
            %
            % Field names are converted to table variable names. If
            % there are substructures, then the variable names
            % have a 'dot' indicating the substructure.
            %
            % 'depends_on' elements are given their own names.
            % Each dependency has a 'depends_on_NAME' variable name
            % and the value is the dependency value.
            %

            s = ndi_document_obj.document_properties;
            if isfield(s,'depends_on')
                s = rmfield(s,'depends_on');
            end
            if isfield(s,'files')
                s = rmfield(s,'files');
            end

            t = table();
            [names,depend] = ndi_document_obj.dependency();
            for i=1:numel(names)
                t_new = cell2table({depend(i).value},'variableNames',{['depends_on_' depend(i).name]});
                t = cat(2,t,t_new);
            end

            abbrev = {};
            abbrevName = fullfile(ndi.common.PathConstants.CommonFolder,'config','ndi_document2table_abbreviations.json');
            if isfile(abbrevName)
                j = vlt.file.textfile2char(abbrevName);
                abbrev = jsondecode(j);
            end

            ts = vlt.data.flattenstruct2table(s,abbrev);

            t = cat(2,t,ts);
        end

        function tf = has_files(ndi_document_obj)
            tf = isfield(ndi_document_obj.document_properties, 'files') ...
                && isstruct(ndi_document_obj.document_properties.files) ...
                && isfield(ndi_document_obj.document_properties.files, 'file_info') ...
                && ~isempty(ndi_document_obj.document_properties.files.file_info);
        end

        function ndi_document_obj = add_file(ndi_document_obj, name, location, options)
            % ADD_FILE - add a file to an ndi.document
            %
            % NDI_DOCUMENT_OBJ = ADD_FILE(NDI_DOCUMENT_OBJ, NAME, LOCATION, ...)
            %
            % Adds a file's information to an ndi.document, for later ingestion
            % into the database. did.document/add_file does the work; see it for
            % NAME, LOCATION and the name/value pairs ingest, delete_original
            % and location_type.
            %
            % This override exists for one thing: NDI has a third location type
            % that did.document does not know about. A LOCATION of the form
            % 'ndic://<datasetId>/<fileUid>' names a file that lives in NDI
            % Cloud and is fetched on demand by the custom file handler in
            % ndi.database.implementations.database.didsqlite. did.document
            % recognizes only 'file' and 'url', so it would read an ndic://
            % location as a local path and default to ingesting it and then
            % deleting the "original" -- a path that does not exist.
            %
            % So detect it here and supply the three defaults did.document
            % cannot know. A value the caller supplied always wins.

            arguments
                ndi_document_obj
                name
                location
                options.ingest = NaN
                options.delete_original = NaN
                options.location_type = NaN
            end

            % did.document's add_file indexes files.file_info directly.
            % ndi.document's used to create the field on first use instead, so
            % a document that reached add_file without it still worked. The
            % constructor now seeds it for a document built from a definition,
            % but one built from a hand-assembled properties struct can still
            % arrive without it, so meet the contract here rather than let an
            % inherited add_file index a field that is not there.
            if isfield(ndi_document_obj.document_properties, 'files') && ...
                    ~isfield(ndi_document_obj.document_properties.files, 'file_info')
                ndi_document_obj = ndi_document_obj.reset_file_info();
            end

            if startsWith(strip(location), 'ndic://', 'IgnoreCase', true)
                if localIsUnsetOption(options.ingest)
                    options.ingest = 0;
                end
                if localIsUnsetOption(options.delete_original)
                    options.delete_original = 0;
                end
                if localIsUnsetOption(options.location_type)
                    options.location_type = 'ndicloud';
                end
            end

            % Whatever is still unset goes up as NaN, which is did.document's
            % own marker for "not given", so passing all three is the same as
            % naming none of them.
            args = namedargs2cell(options);
            ndi_document_obj = add_file@did.document(ndi_document_obj, ...
                name, location, args{:});

        end % add_file

        function [names, depend_struct] = dependency(ndi_document_obj)
            % DEPENDENCY - return names and a structure with all dependencies for an ndi.object
            %
            % [NAMES, DEPEND_STRUCT] = DEPENDENCY(NDI_DOCUMENT_OBJ)
            %
            % Returns in the cell array NAMES the 'name' of all 'depends_on' entries in the ndi.document NDI_DOCUMENT_OBJ.
            % Further, this function returns a structure with all 'name' and 'value' entries in DEPEND_STRUCT.
            %
            names = {};
            depend_struct = vlt.data.emptystruct('name','value');
            hasdependencies = isfield(ndi_document_obj.document_properties,'depends_on') && ...
                ~isempty(ndi_document_obj.document_properties.depends_on);
            if hasdependencies
                names = {ndi_document_obj.document_properties.depends_on.name};
                depend_struct = ndi_document_obj.document_properties.depends_on;
            end
        end % dependency()

        function b = doc_isa(ndi_document_obj, document_class)
            % DOC_ISA - is an ndi.document a member of a particular document_class?
            %
            % B = DOC_ISA(NDI_DOCUMENT_OBJ, DOCUMENT_CLASS)
            %
            % Returns 1 if NDI_DOCUMENT_OBJ or one of its superclasses is a match
            % for DOCUMENT_CLASS. Otherwise returns 0.
            %
            sc = ndi_document_obj.doc_superclass();
            c = ndi_document_obj.doc_class();
            b = any(strcmp(document_class, cat(1,c(:),sc(:))));
        end % doc_isa()

        function c = doc_class(ndi_document_obj)
            % DOC_CLASS what is the document class type of an ndi.document object?
            %
            % C = DOC_CLASS(NDI_DOCUMENT_OBJ)
            %
            % Returns the document class of an ndi.document.
            % (Found at ndi_document_obj.document_properties.document_class.class_name)
            %
            c = ndi_document_obj.document_properties.document_class.class_name;
        end % doc_class()

        function sc = doc_superclass(ndi_document_obj)
            % DOC_SUPERCLASS - return the document superclasses of an ndi.document object
            %
            % SC = DOC_SUPERCLASS(NDI_DOCUMENT_OBJ)
            %
            % Returns the document superclasses of an ndi.document object. SC is a cell
            % array of strings.
            %
            sc = {};
            for i=1:numel(ndi_document_obj.document_properties.document_class.superclasses)
                s = ndi.document(ndi_document_obj.document_properties.document_class.superclasses(i).definition);
                sc{i} = s.doc_class();
            end
            sc = unique(sc); % alphabetize and remove any duplicates
        end % doc_superclass

        function uid = doc_unique_id(ndi_document_obj)
            % DOC_UNIQUE_ID - return the document unique identifier for an ndi.document
            %
            % UID = DOC_UNIQUE_ID(NDI_DOCUMENT_OBJ)
            %
            % Returns the unique id of an ndi.document
            % (Found at NDI_DOCUMENT_OBJ.documentproperties.base.id)
            %
            warning('depricated..use ID() instead')
            uid = ndi_document_obj.document_properties.base.id;
        end % doc_unique_id()


        function uid = session_id(ndi_document_obj)
            % ID - return the document session unique identifier for an ndi.document
            %
            % UID = SESSION_ID (NDI_DOCUMENT_OBJ)
            %
            % Returns the unique session id of an ndi.document
            % (Found at NDI_DOCUMENT_OBJ.documentproperties.base.session_id)
            %
            uid = ndi_document_obj.document_properties.base.session_id;
        end % session_id()
        
        function fuid = get_fuid(ndi_document_obj, filename)
            % GET_FUID - return the file UID for a given filename
            %
            % FUID = GET_FUID(NDI_DOCUMENT_OBJ, FILENAME)
            %
            % Given a FILENAME, this function returns the file UID (FUID)
            % associated with that file in the NDI_DOCUMENT_OBJ.
            % If the file is not found, an empty string is returned.
            %
            fuid = '';

            % is_in_file_list is did.document's, and it reads files.file_info
            % without first checking the field is there. has_files() is the
            % check: false means no file was ever added, so there is no uid to
            % return and nothing to look up.
            if ~ndi_document_obj.has_files()
                return;
            end

            [b, ~, fI_index] = ndi_document_obj.is_in_file_list(filename);
            if ~b || isempty(fI_index)
                return;
            end

            files = ndi_document_obj.document_properties.files;
            locations = files.file_info(fI_index(1)).locations;
            if ~isempty(locations)
                fuid = locations(1).uid;
            end
        end % get_fuid()

        function fl = current_file_list(ndi_document_obj)
            % CURRENT_FILE_LIST - return the list of files that have been associated with an ndi.document
            %
            % FL = CURRENT_FILE_LIST(NDI_DOCUMENT_OBJ)
            %
            % Return a cell array of file names that are associated with an ndi.document object.
            %
            % This list will be a subset of all files possible to add to the document in
            % ndi_document_obj.document_properties.file.file_list, and only includes files that have actually
            % been added in {ndi_document_obj.document_properties.file.file_info.name}.
            fl = {};
            if isfield(ndi_document_obj.document_properties,'files')
                if isfield(ndi_document_obj.document_properties.files,'file_info')
                    if ~isempty(ndi_document_obj.document_properties.files.file_info)
                        fl = {ndi_document_obj.document_properties.files.file_info.name};
                    end
                end
            end
        end %  current_file_list()

        function write(ndi_document_obj, filePrefix, options)
            % WRITE - write the document properties to a file
            %
            % WRITE(NDI_DOCUMENT_OBJ, FILEPREFIX, ...)
            %
            % Writes the document_properties of the NDI_DOCUMENT_OBJ to a JSON file
            % named [FILEPREFIX '.json'].
            %
            % This method accepts name/value pairs:
            % Parameter (default)        | Description
            % ----------------------------------------------------------------------
            % writeLocalFiles (false)    | If true, write associated files to disk
            %                            | named [FILEPREFIX '_' FILENAME].
            % session (ndi.session.empty)| If provided, use this session to read files.
            %                            | If empty and writeLocalFiles is true, tries
            %                            | to copy local files specified in the document.
            %
            arguments
                ndi_document_obj (1,1) ndi.document
                filePrefix (1,:) char
                options.writeLocalFiles (1,1) logical = false
                options.session ndi.session = ndi.session.empty()
            end

            jsonStr = jsonencode(ndi_document_obj.document_properties, 'ConvertInfAndNaN', true, 'PrettyPrint', true);

            fid = fopen([filePrefix '.json'], 'w');
            if fid<0
                error(['Could not open file ' filePrefix '.json for writing.']);
            end
            fprintf(fid, '%s', jsonStr);
            fclose(fid);

            if options.writeLocalFiles
                if isfield(ndi_document_obj.document_properties, 'files') && ...
                        isfield(ndi_document_obj.document_properties.files, 'file_info')

                    files = ndi_document_obj.document_properties.files.file_info;
                    if ~isstruct(files)
                        files = struct([]);
                    end

                    for i=1:numel(files)
                        localfilename = [filePrefix '_' files(i).name];

                        if ~isempty(options.session)
                            % Use session to read
                            bindoc = options.session.database_openbinarydoc(ndi_document_obj, files(i).name);
                            % Read all data
                            fseek(bindoc, 0, 'eof');
                            fsize = ftell(bindoc);
                            fseek(bindoc, 0, 'bof');
                            data = fread(bindoc, fsize, '*uint8');
                            options.session.database_closebinarydoc(bindoc);

                            fid = fopen(localfilename, 'W'); % 'W' for no flushing, faster? Or just 'w'
                            if fid<0
                                error(['Could not open file ' localfilename ' for writing.']);
                            end
                            fwrite(fid, data, 'uint8');
                            fclose(fid);

                        else
                            % Local copy
                            % Find a location that is a file
                            found = false;
                            if isfield(files(i), 'locations')
                                locs = files(i).locations;
                                if isstruct(locs)
                                    for j=1:numel(locs)
                                        if isfield(locs(j), 'location_type') && ...
                                                strcmpi(locs(j).location_type, 'file') && ...
                                                isfield(locs(j), 'location')
                                            copyfile(locs(j).location, localfilename);
                                            found = true;
                                            break;
                                        end
                                    end
                                end
                            end

                            if ~found
                                warning(['Could not find local file location for ' files(i).name]);
                            end
                        end
                    end
                end
            end
        end % write()

        function b = validate(ndi_document_obj)
            % VALIDATE - 0/1 evaluate whether ndi.document object is valid by its schema
            %
            % B = VALIDATE(NDI_DOCUMENT_OBJ)
            %
            % Checks the fields of the ndi.document object against the schema in
            % NDI_DOCUMENT_OBJ.ndi_core_properties.validation_schema and returns 1
            % if the object is valid and 0 otherwise.
            b = 1; % for now, skip this
        end % validate()

    end % methods

    methods (Static)

        function [d,i] = find_doc_by_id(docArray, id)
            % FIND_DOC_BY_ID - find a doc in an array by ID
            %
            % [D,I] = FIND_DOC_BY_ID(DOCARRAY, ID)
            %
            % Given a cell array of ndi.document objects and an
            % ID, return the document D that matches and its
            % index I in DOCARRAY.
            %
            % If no document matches, empty is returned for D, I.
            d = {};
            foundIt = 0;
            if ~iscell(docArray), keyboard; end

            for i=1:numel(docArray)
                if strcmp(id,docArray{i}.document_properties.base.id)
                    d = docArray{i};
                    foundIt = 1;
                    break;
                end
            end

            if ~foundIt
                i = [];
            end

        end % find_doc_by_id

        function [d,i,t] = find_newest(docArray)
            % FIND_NEWEST - find the newest document out an array
            %
            % [D,I,T] = FIND_NEWEST(DOCARRAY)
            %
            % Find the newest document among an array of ndi.document objects.
            %
            % The newest document is returned in D, along with the index I.
            % T is the datestamp of each document as a datetime object.
            %
            for i=1:numel(docArray)
                t(i) = datetime(docArray{i}.document_properties.base.datestamp,'timezone','UTCLeapSeconds');
            end

            [tsort,tsortindex] = sort(t);
            i = tsortindex(end);
            d = docArray{i};
        end % find_newest

        function s = readblankdefinition(jsonfilelocationstring, s)
            % READBLANKDEFINITION - read a blank JSON class definitions from a file location string
            %
            % S = READBLANKDEFINITION(JSONFILELOCATIONSTRING)
            %
            % Given a JSONFILELOCATIONSTRING, this function creates a blank document using the JSON definitions.
            %
            % A JSONFILELOCATIONSTRING can be:
            %    a) a url
            %    b) a filename (full path)
            %       c) a filename referenced with respect to $NDIDOCUMENTPATH
            %
            % See also: DID.DOCUMENT.READJSONFILELOCATION
            %
            % The parsed definitions are memoized per location string (they are
            % static JSON resources read from disk, and this is called for every
            % document and recursively for every superclass). Pass '--clear-cache'
            % as the only argument to reset the memo (e.g. in tests that swap
            % definition files).

            persistent definitionCache
            if isempty(definitionCache)
                definitionCache = containers.Map('KeyType', 'char', 'ValueType', 'any');
            end

            if nargin==1 && (ischar(jsonfilelocationstring) || isstring(jsonfilelocationstring)) ...
                    && strcmp(char(jsonfilelocationstring), '--clear-cache')
                definitionCache = containers.Map('KeyType', 'char', 'ValueType', 'any');
                s = vlt.data.emptystruct;
                return
            end

            % Ensure the DID path constants include the NDI paths on every call
            % (idempotent and cheap), independent of the memo, so a cache hit can
            % never skip this initialization.
            if ~contains('$NDISCHEMAPATH', did.common.PathConstants.definitions.keys)
                ndi.common.PathConstants.updateDIDConstants()
            end

            cacheKey = char(jsonfilelocationstring);
            if isKey(definitionCache, cacheKey)
                % Structs are copy-on-write, so the cached definition cannot be
                % mutated by callers that modify the returned struct.
                s = definitionCache(cacheKey);
                return
            end

            s_is_empty = 0;
            if nargin<2
                s_is_empty = 1;
                s = vlt.data.emptystruct;
            end

            % Step 1): read the information we have here
            
            t = did.document.readjsonfilelocation(jsonfilelocationstring);
            j = jsondecode(t);
            s = j;

            % Step 2): read the information about all the superclasses

            s_super = {};

            if isfield(j,'document_class')
                if isfield(j.document_class,'superclasses')
                    for i=1:numel(j.document_class.superclasses)
                        item = vlt.data.celloritem(j.document_class.superclasses, i, 1);
                        s_super{end+1} = ndi.document.readblankdefinition(item.definition);
                    end
                end
            end

            % Step 3): integrate the superclasses into the document we are building

            for i=1:numel(s_super)
                % merge s and s_super{i}
                % part 1: do we need to merge superclass labels?
                if isfield(s,'document_class') && isfield(s_super{i},'document_class')
                    s.document_class.superclasses = cat(1,s.document_class.superclasses(:),...
                        s_super{i}.document_class.superclasses(:));
                    [dummy,unique_indexes] = unique({s.document_class.superclasses.definition});
                    s.document_class.superclasses = s.document_class.superclasses(unique_indexes);
                else
                    error(['Documents lack ''document_class'' fields.']);
                end

                s_super{i} = rmfield(s_super{i},'document_class');

                % part 2: merge dependencies
                if isfield(s,'depends_on') && isfield(s_super{i},'depends_on') % if only s or super_s has it, merge does it right
                    s.depends_on = cat(1,s.depends_on(:),s_super{i}.depends_on(:));
                    s_super{i} = rmfield(s_super{i},'depends_on');
                    [dummy,unique_indexes] = unique({s.depends_on.name});
                    s.depends_on= s.depends_on(unique_indexes);
                else
                    % regular vlt.data.structmerge is fine, will use 'depends_on' field of whichever structure has it, or none
                end

                % part 3: merge file_list
                if isfield(s,'files') && isfield(s_super{i},'files') % if only s or super_s has it, merge handles it fine
                    s_has = isfield(s.files,'file_list');
                    ssuper_has = isfield(s_super{i}.files,'file_list');
                    if ~ssuper_has % just merge whatever s has
                        % use s's version in the merge
                        s_super{i} = rmfield(s_super{i},'files');
                    elseif ~s_has && ssuper_has
                        s = rmfield(s,'files');
                    else % they both have it
                        s.files.file_list = cat(1,s.files.file_list(:),s_super{i}.files.file_list(:));
                        s_super{i} = rmfield(s_super{i},'files');
                        [dummy,unique_indexes] = unique(s.files.file_list);
                        s.files.file_list = s.files.file_list(unique_indexes);
                    end
                else
                    % nothing to do, only one has it and merge will do it
                end

                % now do the merge
                s = vlt.data.structmerge(s,s_super{i});
            end

            definitionCache(cacheKey) = s;
        end % readblankdefinition()

    end % methods Static
end % classdef

function tf = localIsUnsetOption(value)
    % ADD_FILE's options use NaN to mean "not given". A location_type the
    % caller did supply is a char, and isnan is not a safe test on one, so
    % check that it is a numeric scalar before asking.
    tf = isnumeric(value) && isscalar(value) && isnan(value);
end
