function datasetDateObj = convertDatasetDate(cloudDataset)
    % Parse dates from ISO format
    try
        publicationDate = datetime(cloudDataset.createdAt, ...
            'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''');
    catch
        % Fallback to current date if parsing fails
        publicationDate = datetime('now');
    end
    
    yearStr = num2str(year(publicationDate));
    monthStr = sprintf('%02d', month(publicationDate));
    dayStr = sprintf('%02d', day(publicationDate));
    
    % Create publication_date object:
    publicationDate = crossref.model.PublicationDate(...
        'Year', yearStr, ...
        'Month', monthStr, ...
        'Day', dayStr, ...
        'MediaType', crossref.enum.MediaType.online ...
    );
    
    createdYMD = timestampToYearMonthDay(cloudDataset.createdAt);
    updatedYMD = timestampToYearMonthDay(cloudDataset.createdAt);

    datasetDateObj = crossref.model.DatabaseDate(...
        "PublicationDate", publicationDate, ...
        "CreationDate", crossref.model.CreationDate(...
            "Year", string(createdYMD(1)), ...
            "Month", string(createdYMD(2)), ...
            "Day", string(createdYMD(3)), ...
            "MediaType", "online"), ...
        "UpdateDate", crossref.model.UpdateDate(...
            "Year", string(updatedYMD(1)), ...
            "Month", string(updatedYMD(2)), ...
            "Day", string(updatedYMD(3)), ...
            "MediaType", "online") );
end

function ymd = timestampToYearMonthDay(timestamp)
    datetimeValue = datetime(timestamp, 'InputFormat', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''');
    ymd = [year(datetimeValue), month(datetimeValue), day(datetimeValue)];
end
