function nsd_probetype2objectinit
% NSD_PROBETYPE2OBJECTINIT - Initializes the NSD_PROBETYPE2OBJECT global variable in NSD package
%
% NSD_PROBETYPE2OBJECTINIT
%
% Initializes the NSD_PROBETYPE2OBJECT structure. The structure has two fields,
% 'type' and 'classname'. Each entry describes the NSD_PROBE subclass to use to
% create an NSD_PROBE object for the given NSD_EPOCHCONTENTS type.
% 
% Use TYPE NSD_PROBETYPE2OBJECTINIT to see the structure

nsd_globals

nsd_probetype2object_data = { ...
	'n-trode'		'nsd_probe_mfdaq'          ; ...
	'electrode-$'		'nsd_probe_mfdaq'          ; ...
	'patch'			'nsd_probe_mfdaq'          ; ...
	'patch-Vm'		'nsd_probe_mfdaq'          ; ...
	'patch-I'		'nsd_probe_mfdaq'          ; ...
	'patch-attached'	'nsd_probe_mfdaq'          ; ...
	'sharp'			'nsd_probe_mfdaq'          ; ...
	'sharp-Vm'		'nsd_probe_mfdaq'          ; ...
	'sharp-I'		'nsd_probe_mfdaq'          ; ...
	'wide-field-imaging'	'nsd_probe_timage'         ; ...
	'2-photon-imaging'	'nsd_probe_timage'         ; ...
	'1-photon-imaging'	'nsd_probe_timage'         ; ...
	'brightfield-imaging'	'nsd_probe_image'          ; ...
	'lick-spout'		'nsd_probe_mfdaq'          ; ...
	'intraoral-cannula'	'nsd_probe_mfdaq'          ; ...
	'reward-well'		'nsd_probe_mfdaq'          ; ...
	'stimulator'		'nsd_probe_stimulator'     ; ...
};

nsd_probetype2object = struct('type', nsd_probetype2object_data(:,1), 'classname', nsd_probetype2object_data(:,2));


