classdef TestReadGEF < matlab.unittest.TestCase
    % TestReadGEF - readGEF against synthetic GEFs written by h5py.
    %
    % The fixtures are written by NDI-python's library, not by MATLAB, and
    % are regenerated by make_gef_fixtures.py in this folder. That is the
    % same arrangement conformance_tile.bin uses, and for the same reason:
    % readGEF's job is to cope with files it did not write, so a fixture
    % built by the same language and library as the reader tests very
    % little.
    %
    % Each fixture varies ONE thing readGEF has to probe for, so a failure
    % names the probe that broke. Three of them exist because the failure
    % they catch is silent:
    %
    %   * gef_basic writes the extent attributes on the BIN GROUP, not the
    %     file root. Probing only the root yields a 1x1 pyramid, and a
    %     fixture that writes them at the root agrees with that bug instead
    %     of catching it -- so gef_rootattrs covers the root case
    %     separately rather than being the only case.
    %   * gef_badbox's attribute box does not contain the records. It must
    %     lose to the data rather than silently shifting the origin.
    %   * gef_uint8 stores counts as uint8. min() on a uint8 array
    %     saturates at 255, so a reader that clips in the narrow type turns
    %     large counts into 255 without erroring.
    %
    % The records are the same in every fixture: 6 records over 3 genes,
    % gene blocks of 3, 1 and 2, x in 10..31 and y in 50..71. y is offset
    % from x so a transposing reader diverges rather than coincidentally
    % agreeing.

    properties
        dir
    end

    methods (TestClassSetup)
        function locate(testCase)
            testCase.dir = fileparts(mfilename('fullpath'));
        end
    end

    methods (Test)

        function testReadsRecordsAndGenes(testCase)
            [x,y,gi,c,id,nm,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('basic'));

            testCase.verifyEqual(numel(x), 6);
            testCase.verifyEqual(meta.nRecords, 6);
            testCase.verifyEqual(meta.nGenes, 3);
            testCase.verifyEqual(id, {'ENSG1';'ENSG2';'ENSG3'});
            testCase.verifyEqual(nm, {'Aaa';'Bbb';'Ccc'});

            % gene_index is ZERO-BASED and follows the offset blocks:
            % gene 0 owns 3 records, gene 1 owns 1, gene 2 owns 2.
            testCase.verifyEqual(gi, int32([0;0;0;1;2;2]));
            testCase.verifyClass(x,'int32');
            testCase.verifyClass(c,'uint16');
            testCase.verifyEqual(double(x(:))', [10 11 12 20 30 31]);
            testCase.verifyEqual(double(y(:))', [50 51 52 60 70 71]);
            testCase.verifyEqual(double(c(:))', [1 2 200 7 8 9]);
        end

        function testChipSerialAndResolution(testCase)
            [~,~,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('basic'));
            testCase.verifyEqual(meta.chipSerial,'TESTCHIP01');
            testCase.verifyEqual(meta.resolutionNm, 500);
        end

        function testExtentAttributesAreFoundOffTheRoot(testCase)
            % Written on the bin group. A root-only probe would miss them
            % and fall back to the data, reporting 'data'.
            [~,~,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('basic'));
            testCase.verifyEqual(meta.box, [0 0 99 99]);
            testCase.verifyTrue(contains(meta.boxSource,'/geneExp/bin1'));
        end

        function testExtentAttributesAtTheRootAlsoWork(testCase)
            [~,~,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('rootattrs'));
            testCase.verifyEqual(meta.box, [0 0 99 99]);
            testCase.verifyTrue(contains(meta.boxSource,'attrs'));
        end

        function testDisagreeingAttributesLoseToTheData(testCase)
            % A box that does not contain the records is wrong; the data
            % cannot be wrong about its own extent.
            [x,y,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('badbox'));
            testCase.verifyEqual(meta.boxSource,'data');
            testCase.verifyEqual(meta.box, ...
                [double(min(x)) double(min(y)) double(max(x)) double(max(y))]);
        end

        function testCountsClipInAWideType(testCase)
            % uint8 counts: a reader clipping in the narrow type saturates
            % every one of these at 255 and reports nothing wrong.
            [~,~,~,c,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('uint8'));
            testCase.verifyEqual(double(max(c)), 200);
            testCase.verifyEqual(meta.nCountsClamped, 0);
        end

        function testCountCeilingClampsAndReports(testCase)
            [~,~,~,c,~,~,meta] = ndi.fun.doc.gene.readGEF( ...
                testCase.gef('basic'), 'countCeiling', 5);
            testCase.verifyEqual(double(max(c)), 5);
            testCase.verifyEqual(meta.nCountsClamped, 4);   % 200, 7, 8, 9
        end

        function testAlternateFieldNamesAreProbed(testCase)
            [x,~,~,c,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('altfields'));
            testCase.verifyEqual(meta.fields.x,'X');
            testCase.verifyEqual(meta.fields.count,'MIDCount');
            testCase.verifyEqual(double(x(:))', [10 11 12 20 30 31]);
            testCase.verifyEqual(double(c(:))', [1 2 200 7 8 9]);
        end

        function testAlternateLayoutIsProbed(testCase)
            [~,~,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('altroot'));
            testCase.verifyEqual(meta.root,'/wholeExp/bin1');
            testCase.verifyTrue(endsWith(meta.exprDataset,'cellBin'));
        end

        function testStatGeneCrossCheck(testCase)
            % SAW's own per-gene MIDcount is a THIRD source for a number we
            % derive ourselves. The fixture's values are the true per-gene
            % sums, so a reader that mis-assigns records to genes disagrees.
            [~,~,gi,c,~,~,meta] = ndi.fun.doc.gene.readGEF(testCase.gef('basic'));
            testCase.verifyEqual(meta.statTotals, [203;7;17]);

            derived = accumarray(double(gi)+1, double(c), [3 1]);
            testCase.verifyEqual(derived, meta.statTotals, ...
                'per-gene totals must agree with SAW''s own count');
        end

        function testProbeOnlyReadsNoRecords(testCase)
            [x,y,gi,c,id,~,meta] = ndi.fun.doc.gene.readGEF( ...
                testCase.gef('basic'), 'probeOnly', true);

            testCase.verifyEmpty(x); testCase.verifyEmpty(y);
            testCase.verifyEmpty(gi); testCase.verifyEmpty(c);

            % The gene table and the record COUNT are still exact: both come
            % from the gene table, which probeOnly does read. That is the
            % point -- a GUI can show what is in a file without the long read.
            testCase.verifyEqual(meta.nRecords, 6);
            testCase.verifyEqual(meta.nGenes, 3);
            testCase.verifyEqual(id, {'ENSG1';'ENSG2';'ENSG3'});

            % The box is reported UNVALIDATED: with no records there is
            % nothing to check it against, and a caller must be able to tell.
            testCase.verifyTrue(contains(meta.boxSource,'unvalidated'));
        end

        function testProbeOnlyStillNamesTheFields(testCase)
            % The field probe must not depend on reading records, or a GUI
            % learns a file is unreadable only after the long read.
            [~,~,~,~,~,~,meta] = ndi.fun.doc.gene.readGEF( ...
                testCase.gef('altfields'), 'probeOnly', true);
            testCase.verifyEqual(meta.fields.x,'X');
            testCase.verifyEqual(meta.fields.count,'MIDCount');
        end

        function testMaxGenesLimits(testCase)
            [~,~,gi,~,id,~,meta] = ndi.fun.doc.gene.readGEF( ...
                testCase.gef('basic'), 'maxGenes', 2);
            testCase.verifyEqual(meta.nGenes, 2);
            testCase.verifyEqual(meta.nGenesInFile, 3);
            testCase.verifyEqual(numel(id), 2);
            testCase.verifyEqual(meta.nRecords, 4);      % 3 + 1
            testCase.verifyEqual(max(gi), int32(1));
        end

        function testNotAGefIsNamed(testCase)
            testCase.verifyError( ...
                @() ndi.fun.doc.gene.readGEF(testCase.gef('notagef')), ...
                'NDI:gene:readGEF:noGeneExpressionPair');
        end

    end

    methods (Access = private)
        function f = gef(testCase, which)
            f = fullfile(testCase.dir, ['gef_' which '.gef']);
            testCase.assertTrue(isfile(f), ...
                sprintf(['%s is missing; regenerate the fixtures with ' ...
                         'make_gef_fixtures.py in this folder.'], f));
        end
    end
end
