function testToolbox(varargin)
    projectRootDir = nditools.projectdir();
    matbox.installRequirements(fullfile(projectRootDir, 'tests'))
    matbox.tasks.testToolbox(projectRootDir, ...
        "SourceFolderName", "src", ...
        "TestsFolderName", "tests", ...
        "Verbosity", "Terse", ...
        varargin{:})
end
