function testToolbox(varargin)
    projectRootDir = nditools.projectdir();
    matbox.installRequirements(fullfile(projectRootDir, 'tests'))
    matbox.tasks.testToolbox(projectRootDir, ...
        "SourceFolderName", "+ndi", ...
        "ToolsFolderName", "", ...
        "Verbosity", "Terse", ...
        varargin{:})
end
