function summaryTable = analyzeZipLog()
% ANALYZE_ZIP_LOG - Summarizes the contents of the zip_log.csv file.
%
%   SUMMARYTABLE = analyzeZipLog()
%
%   This function reads the 'zip_log.csv' file generated by the NDI upload
%   process. It analyzes the contents and produces a summary table that
%   details the composition of each zip archive created during the upload.
%
%   The function returns a table with one row for each unique zip file,
%   containing the following columns:
%     - 'ZipFileName': The name of the zip archive.
%     - 'NumFiles': The number of individual files included in that archive.
%     - 'TotalUncompressedBytes': The sum of the uncompressed sizes of all
%       files within that archive.
%
%   This is useful for quickly verifying the contents and total size of each
%   upload batch.
%
%   See also: readtable, groupsummary

    log_folder = ndi.common.PathConstants.LogFolder;
    zip_log_path = fullfile(log_folder, 'zip_log.csv');

    if ~isfile(zip_log_path)
        error('The zip log file "%s" does not exist. Please run the upload function with DebugLog enabled first.', zip_log_path);
    end

    fprintf('Reading and analyzing zip log file: %s\n', zip_log_path);

    % Use specific import options to preserve original headers
    opts = delimitedTextImportOptions("NumVariables", 3);
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";
    opts.VariableNames = ["ZipFile", "ZippedFile", "UncompressedBytes"];
    opts.VariableTypes = ["string", "string", "double"];
    zipLogTable = readtable(zip_log_path, opts);

    % **THE FIX IS HERE:**
    % We only need to specify 'sum' for the data variable.
    % The count of items is returned by default in the 'GroupCount' column.
    summaryTable = groupsummary(zipLogTable, 'ZipFile', 'sum', 'UncompressedBytes');

    % Rename the columns for clarity
    summaryTable.Properties.VariableNames{'ZipFile'} = 'ZipFileName';
    summaryTable.Properties.VariableNames{'sum_UncompressedBytes'} = 'TotalUncompressedBytes';
    summaryTable.Properties.VariableNames{'GroupCount'} = 'NumFiles';

    fprintf('Analysis complete.\n');
end