classdef NDIButtonLight < uim.style.buttonScheme
    
    properties (Constant)
        
        HighlightedOn = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        HighlightedOff = struct(...
            'ForegroundColor', hex2rgb('#002054'), ...
            'BackgroundColor', ndi.dataset.gui.WizardTheme.FigureBgColor, ...
            'BackgroundAlpha', 1, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        On = struct(...
            'ForegroundColor', ones(1,3) * 0.9, ...
            'BackgroundColor', ones(1,3) * 0.4, ...
            'BackgroundAlpha', 0.4, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
        Off = struct(...
            'ForegroundColor', hex2rgb('#002054'), ...
            'BackgroundColor', ndi.dataset.gui.WizardTheme.FigureBgColor, ...
            'BackgroundAlpha', 0.8, ...
            'BorderColor', 'k', ...
            'BorderWidth', 0.5 )
    end
end
