function logger = getLogger()
    
    persistent cachedLogger
    if isempty(cachedLogger)
        cachedLogger = vlt.app.log(...
	        'system_logfile', fullfile(ndi.common.PathConstants.LogFolder, 'system.log'), ...
	        'error_logfile', fullfile(ndi.common.PathConstants.LogFolder, 'error.log'), ...
	        'debug_logfile', fullfile(ndi.common.PathConstants.LogFolder, 'debug.log'), ...
	        'system_verbosity', 5, ...
	        'error_verbosity', 5, ...
	        'debug_verbosity', 5, ...
	        'log_name', 'ndi', ...
	        'log_error_behavior', 'warning');
    end
    logger = cachedLogger;
end