function databaseMetadata = createDatabaseMetadata()
    dataBaseTitle = crossref.model.Titles(...
        'Title', ndi.cloud.admin.crossref.Constants.DatabaseTitle ...
    );
    
    % Create database_metadata object
    databaseMetadata = crossref.model.DatabaseMetadata(...
        'Titles', dataBaseTitle, ...
        'Language', 'eng' ...
    );
end
