function doiBatch = createDoiBatchSubmission(dataset)

    % Create database object % Todo: Support multiple datasets?
    database = crossref.model.Database(...
        'DatabaseMetadata', ndi.cloud.admin.crossref.createDatabaseMetadata(), ...
        'Dataset', dataset ...
    );
    
    % Create body object
    body = crossref.model.Body(...
        'Database', database ...
    );
    
    % Create doi_batch object
    doiBatch = crossref.model.DoiBatch(...
        'Head', ndi.cloud.admin.crossref.createDoiBatchHeadElement(), ...
        'Body', body ...
    );
end
