function databaseMetadata = createDatabaseMetadata()
% createDatabaseMetadata - Create database metadata for NDI Cloud

    % Create titles object
    dataBaseTitle = crossref.model.Titles(...
        "Title", ndi.cloud.admin.crossref.Constants.DatabaseTitle );
    
    % Create database_organization object
    databaseContributor = crossref.model.Organization(...
        "Name", ndi.cloud.admin.crossref.Constants.DatabaseOrganization, ...
        "Sequence", "first" );

    % Create database_date object
    creationDateStr = ndi.cloud.admin.crossref.Constants.DatabaseCreationDate;
    databaseDate = crossref.model.DatabaseDate(...
        "CreationDate", crossref.model.CreationDate(...
            "Year", creationDateStr(1), ...
            "Month", creationDateStr(2), ...
            "Day", creationDateStr(3), ...
            "MediaType", "online"), ...
        "PublicationDate", crossref.model.PublicationDate(...
            "Year", creationDateStr(1), ...
            "Month", creationDateStr(2), ...
            "Day", creationDateStr(3), ...
            "MediaType", "online") );

    % Create doi_data object
    doiData = crossref.model.DoiData(...
        "Doi", ndi.cloud.admin.crossref.Constants.DatabaseDOI, ...
        "Resource", ndi.cloud.admin.crossref.Constants.DatabaseURL );

    % Create database_metadata object
    databaseMetadata = crossref.model.DatabaseMetadata(...
        "Titles", dataBaseTitle, ...
        "Description", ndi.cloud.admin.crossref.Constants.DatabaseDescription, ...
        "Contributors", crossref.model.Contributors("Items", {databaseContributor}), ...
        "DatabaseDate", databaseDate, ...
        "DoiData", doiData, ...
        "Language", "eng" );
end
