function databasehierarchy = databasehierarchyinit()
    % DATABASEHIERARCHYINIT - Initializes the list of databases to try
    %
    % ndi.database.fun.databasehierarchyinit
    %
    % Use TYPE ndi.probe.fun.probetype2objectinit to see the structure
    % Question: What is the above command?

    databasehierarchy = struct( ...
        'extension',    'ndi.dumbjsondb.json', ...
        'code',         'db=ndi.database.implementations.database.matlabdumbjsondb2(''FILEPATH'', ''SESSION_REFERENCE'', ''load'',''FILENAME'');',  ...
        'newcode',      'db=ndi.database.implementations.database.matlabdumbjsondb2(''FILEPATH'', ''SESSION_REFERENCE'', ''new'',''FILEPATHndi.dumbjsondb.json'');' ...
        );

    databasehierarchy = struct( ...
        'extension',    'ndi.dumbjsondb.json', ...
        'code',         'db=ndi.database.implementations.database.didsqlite(''FILEPATH'', ''SESSION_REFERENCE'', ''load'',''FILENAME'');',  ...
        'newcode',      'db=ndi.database.implementations.database.didsqlite(''FILEPATH'', ''SESSION_REFERENCE'', ''new'',''FILEPATHndi.dumbjsondb.json'');' ...
        );
