classdef PlotProbeGeometryTest < matlab.unittest.TestCase

    methods (Test)
        function testStructInput(testCase)
            % Test with a simple probe_geometry struct
            pg = struct( ...
                'site_locations_leftright', [0; 0; 0; 0], ...
                'site_locations_depth', [0; 25; 50; 75], ...
                'shank_id', [1; 1; 1; 1], ...
                'unit', 'um', ...
                'probe_model', '', ...
                'manufacturer', '', ...
                'has_planar_contour', 0, ...
                'contour_x', [], ...
                'contour_y', [] ...
            );

            fig = figure('Visible', 'off');
            cleanup = onCleanup(@() close(fig));
            ax = axes(fig);

            h = ndi.fun.probe.plotProbeGeometry(pg, 'axes', ax);

            testCase.verifyTrue(isvalid(h.sites), 'Scatter handle should be valid');
            testCase.verifyTrue(isempty(h.contour), 'Contour handle should be empty when no contour');
            testCase.verifyEqual(h.ax, ax, 'Should use provided axes');

            % verify site positions match input
            testCase.verifyEqual(h.sites.XData(:), pg.site_locations_leftright(:), ...
                'X data should match site_locations_leftright');
            testCase.verifyEqual(h.sites.YData(:), pg.site_locations_depth(:), ...
                'Y data should match site_locations_depth');
        end

        function testMultiShank(testCase)
            % Test with multiple shanks to verify coloring
            pg = struct( ...
                'site_locations_leftright', [-50; -50; 50; 50], ...
                'site_locations_depth', [0; 25; 0; 25], ...
                'shank_id', [1; 1; 2; 2], ...
                'unit', 'um', ...
                'probe_model', '', ...
                'manufacturer', '', ...
                'has_planar_contour', 0, ...
                'contour_x', [], ...
                'contour_y', [] ...
            );

            fig = figure('Visible', 'off');
            cleanup = onCleanup(@() close(fig));
            ax = axes(fig);

            h = ndi.fun.probe.plotProbeGeometry(pg, 'axes', ax);

            testCase.verifyTrue(isvalid(h.sites), 'Scatter handle should be valid');
            testCase.verifyEqual(numel(h.sites.XData), 4, 'Should plot all 4 sites');
        end

        function testWithContour(testCase)
            % Test that contour is plotted when present
            pg = struct( ...
                'site_locations_leftright', [0; 0], ...
                'site_locations_depth', [10; 20], ...
                'shank_id', [1; 1], ...
                'unit', 'um', ...
                'probe_model', 'TestProbe', ...
                'manufacturer', 'TestMfg', ...
                'has_planar_contour', 1, ...
                'contour_x', [-5; 5; 5; -5; -5], ...
                'contour_y', [0; 0; 30; 30; 0] ...
            );

            fig = figure('Visible', 'off');
            cleanup = onCleanup(@() close(fig));
            ax = axes(fig);

            h = ndi.fun.probe.plotProbeGeometry(pg, 'axes', ax);

            testCase.verifyTrue(isvalid(h.contour), 'Contour handle should be valid');
            testCase.verifyEqual(h.contour.XData(:), pg.contour_x(:), ...
                'Contour X data should match');
            testCase.verifyEqual(h.contour.YData(:), pg.contour_y(:), ...
                'Contour Y data should match');

            % verify title includes manufacturer and model
            testCase.verifyEqual(ax.Title.String, 'TestMfg TestProbe');
        end

        function testNoShankId(testCase)
            % Test with no shank_id field
            pg = struct( ...
                'site_locations_leftright', [0; 10], ...
                'site_locations_depth', [0; 20], ...
                'unit', 'mm', ...
                'has_planar_contour', 0, ...
                'contour_x', [], ...
                'contour_y', [] ...
            );

            fig = figure('Visible', 'off');
            cleanup = onCleanup(@() close(fig));
            ax = axes(fig);

            h = ndi.fun.probe.plotProbeGeometry(pg, 'axes', ax);

            testCase.verifyTrue(isvalid(h.sites), 'Should plot without shank_id');
            testCase.verifySubstring(ax.XLabel.String, 'mm', 'Should use provided unit');
        end

        function testCustomMarkerSize(testCase)
            % Test that marker_size parameter is respected
            pg = struct( ...
                'site_locations_leftright', [0; 0], ...
                'site_locations_depth', [0; 25], ...
                'shank_id', [1; 1], ...
                'unit', 'um', ...
                'has_planar_contour', 0, ...
                'contour_x', [], ...
                'contour_y', [] ...
            );

            fig = figure('Visible', 'off');
            cleanup = onCleanup(@() close(fig));
            ax = axes(fig);

            h = ndi.fun.probe.plotProbeGeometry(pg, 'axes', ax, 'marker_size', 100);

            testCase.verifyEqual(h.sites.SizeData, 100, 'Marker size should be 100');
        end
    end
end
