classdef ensembleFilterCases
    % ensembleFilterCases - shared, self-describing ndi.fun.ensemble.filter symmetry battery
    %
    %   MATLAB counterpart of tests/symmetry/fun/ensemble_filter_cases.py. Both
    %   language ports run the SAME case list -- each case identified by an
    %   ASCII case NAME -- through their own real ndi.fun.ensemble.filter, then
    %   write the recorded outputs to
    %
    %     <tempdir>/NDI/symmetryTest/<matlabArtifacts|pythonArtifacts>/fun/
    %              ensembleFilter/testEnsembleFilterArtifacts/
    %              ensembleFilterCases.json
    %
    %   The on-disk schema is documented in
    %   tests/+ndi/+symmetry/FUN_CASES_SCHEMA.md, section 10. READ THAT FILE
    %   before changing anything here.
    %
    %   This is a SEPARATE helper from ndi.symmetry.fun.cases rather than more
    %   batteries inside it, for the reason parseTextCases is: cases.m is
    %   already 1238 lines. The canonical value grammar (render / renderSequence)
    %   and the artifact I/O (writeCases / loadCases / indexByName / asCellStr /
    %   asChar / errorId) are reused from ndi.symmetry.fun.cases, so the grammar
    %   stays single-sourced and only the battery is new.
    %
    %   WHAT THIS BATTERY IS FOR
    %   ndi.fun.ensemble.filter is the one function in the +ensemble package
    %   that is pure and in-memory: no session, no database, no clocks. The
    %   rules themselves are stated in the MATLAB help but each is easy to
    %   invert in a port:
    %
    %     * includes are a UNION across names / ids / index / Keep
    %     * excludes always win over includes
    %     * IncludeIndex is 1-based on BOTH sides (a deliberate choice -- the
    %       Python port keeps MATLAB's 1-based indexing so the same case list
    %       drives both languages)
    %     * the activity matrix has its all-zero trailing columns trimmed
    %       afterwards EXCEPT when nothing is kept, where MATLAB's isempty
    %       guard returns early and the 0-by-Smax width survives
    %
    %   Each case pins one of those rules. expectedShape is compared alongside
    %   expectedActivity so the isempty-guard asymmetry cannot drift from
    %   either side while the (empty) values still happen to agree.
    %
    %   WHY ACTIVITY IS ENCODED ROW BY ROW
    %   The activity matrix is 2-D. Section 3 of the schema rules a 2-D matrix
    %   out of the canonical grammar because MATLAB's column-major and Python's
    %   row-major iteration render one the wrong way round. Rows are 1-D
    %   though, so the battery encodes activity as a cell array of rendered
    %   row sequences -- exactly the pattern parseText uses for inputRendered.
    %
    %   See also: ndi.symmetry.fun.cases,
    %     ndi.symmetry.makeArtifacts.fun.ensembleFilter,
    %     ndi.symmetry.readArtifacts.fun.ensembleFilter

    methods (Static)

        % ----------------------------------------------------------------
        % the battery
        % ----------------------------------------------------------------

        function c = newCase(name, note, mirrors, neuronIds, neuronNames, activity, ...
                includeNames, excludeNames, includeIndex, excludeIndex, ...
                includeIds, excludeIds, keepLogical, keepIndex, ...
                expStatus, expIds, expNames, expActivity, expShape)
            % NEWCASE - one case definition, with the field order fixed.
            %
            %   activity, expActivity  1xR cell of 1xC numeric row vectors
            %                         (one entry per neuron row; empty
            %                         when there are no rows to record)
            %   keepLogical           1xN logical row vector, or []
            %   keepIndex             1xK double row vector of 1-based
            %                         indices, or []
            %   expShape              [rows cols], or [] for an error case
            %
            %   Only one of keepLogical / keepIndex is non-empty per case: they
            %   both map onto the Keep name/value argument and having both
            %   populated would be ambiguous.
            c = struct( ...
                'name', name, ...
                'note', note, ...
                'mirrors', mirrors, ...
                'neuronIds', {neuronIds}, ...
                'neuronNames', {neuronNames}, ...
                'activity', {activity}, ...
                'includeNames', {includeNames}, ...
                'excludeNames', {excludeNames}, ...
                'includeIndex', includeIndex, ...
                'excludeIndex', excludeIndex, ...
                'includeIds', {includeIds}, ...
                'excludeIds', {excludeIds}, ...
                'keepLogical', keepLogical, ...
                'keepIndex', keepIndex, ...
                'expectedStatus', expStatus, ...
                'expectedIds', {expIds}, ...
                'expectedNames', {expNames}, ...
                'expectedActivity', {expActivity}, ...
                'expectedShape', expShape);
        end % newCase

        function defs = definitions()
            % DEFINITIONS - the 15-case battery, as a 1xN struct array.
            n = @ndi.symmetry.fun.ensembleFilterCases.newCase;

            % The workhorse fixture: 4 neurons; row i has i spikes, so
            % neuron 3 pins the widest column and trimming is observable when
            % anyone else is kept alone. (See the Python module for the same.)
            ids   = {'id1', 'id2', 'id3', 'id4'};
            names = {'A', 'B', 'C', 'D'};
            act   = {[11 0 0], [21 22 0], [31 32 33], [41 0 0]};

            defs = n('seed', '', '', {}, {}, {}, {}, {}, [], [], {}, {}, [], [], ...
                'ok', {}, {}, {}, [0 0]);
            defs(1) = [];

            defs(end+1) = n('noCriteriaKeepsAll', ...
                ['With no criteria the whole ensemble comes back unchanged ' ...
                 'and num_neurons is preserved.'], ...
                'testNoOptionsKeepsAll', ...
                ids, names, act, ...
                {}, {}, [], [], {}, {}, [], [], ...
                'ok', ids, names, act, [4 3]);

            defs(end+1) = n('includeNamesBasic', ...
                ['IncludeNames keeps only the named neurons; trailing ' ...
                 'columns are trimmed to the widest surviving row.'], ...
                'testIncludeNames', ...
                ids, names, act, ...
                {'B','D'}, {}, [], [], {}, {}, [], [], ...
                'ok', {'id2','id4'}, {'B','D'}, {[21 22], [41 0]}, [2 2]);

            defs(end+1) = n('excludeNamesBasic', ...
                'ExcludeNames drops the named neurons; every other row survives.', ...
                'testExcludeNames', ...
                ids, names, act, ...
                {}, {'A'}, [], [], {}, {}, [], [], ...
                'ok', {'id2','id3','id4'}, {'B','C','D'}, ...
                {[21 22 0], [31 32 33], [41 0 0]}, [3 3]);

            defs(end+1) = n('includeIndexBasic', ...
                ['IncludeIndex is 1-based on BOTH sides -- a deliberate ' ...
                 'choice so the same case list drives both languages.'], ...
                'testIncludeIndex', ...
                ids, names, act, ...
                {}, {}, [1 3], [], {}, {}, [], [], ...
                'ok', {'id1','id3'}, {'A','C'}, {[11 0 0], [31 32 33]}, [2 3]);

            defs(end+1) = n('excludeIndexBasic', ...
                'ExcludeIndex takes 1-based positions too.', ...
                'testExcludeIndex', ...
                ids, names, act, ...
                {}, {}, [], 2, {}, {}, [], [], ...
                'ok', {'id1','id3','id4'}, {'A','C','D'}, ...
                {[11 0 0], [31 32 33], [41 0 0]}, [3 3]);

            defs(end+1) = n('includeIdsBasic', ...
                'IncludeIds matches on the element document id, not the name.', ...
                'testIncludeIds', ...
                ids, names, act, ...
                {}, {}, [], [], {'id2','id4'}, {}, [], [], ...
                'ok', {'id2','id4'}, {'B','D'}, {[21 22], [41 0]}, [2 2]);

            defs(end+1) = n('excludeIdsBasic', ...
                'ExcludeIds drops by element id.', ...
                'testExcludeIds', ...
                ids, names, act, ...
                {}, {}, [], [], {}, {'id3'}, [], [], ...
                'ok', {'id1','id2','id4'}, {'A','B','D'}, ...
                {[11 0], [21 22], [41 0]}, [3 2]);

            defs(end+1) = n('keepLogicalMask', ...
                ['Keep with a length-N boolean mask; equivalent to ' ...
                 'IncludeIndex on the true positions.'], ...
                'testKeepLogicalMask', ...
                ids, names, act, ...
                {}, {}, [], [], {}, {}, logical([1 0 1 0]), [], ...
                'ok', {'id1','id3'}, {'A','C'}, {[11 0 0], [31 32 33]}, [2 3]);

            defs(end+1) = n('keepIndexVectorOrderFollowsEnsemble', ...
                ['Keep as an INDEX VECTOR; the argument order [4, 2] does ' ...
                 'NOT set the output order -- the kept neurons come back in ' ...
                 'the ensemble''s own order.'], ...
                'testKeepIndexVector', ...
                ids, names, act, ...
                {}, {}, [], [], {}, {}, [], [4 2], ...
                'ok', {'id2','id4'}, {'B','D'}, {[21 22], [41 0]}, [2 2]);

            defs(end+1) = n('includesAreAUnion', ...
                ['The kept set is the UNION of every include criterion; ' ...
                 'here a name, an id and an index reach three different ' ...
                 'neurons and all three survive.'], ...
                'testIncludeUnionThenExclude', ...
                ids, names, act, ...
                {'A'}, {}, 2, [], {'id4'}, {}, [], [], ...
                'ok', {'id1','id2','id4'}, {'A','B','D'}, ...
                {[11 0], [21 22], [41 0]}, [3 2]);

            defs(end+1) = n('excludeBeatsIncludeOnSameNeuron', ...
                ['An exclude always removes from the kept set, INCLUDING ' ...
                 'a neuron an include criterion just put there. This is the ' ...
                 'one rule a reader is most likely to invert.'], ...
                'testIncludeUnionThenExclude', ...
                ids, names, act, ...
                {'A','B','C'}, {'B'}, [], [], {}, {}, [], [], ...
                'ok', {'id1','id3'}, {'A','C'}, {[11 0 0], [31 32 33]}, [2 3]);

            defs(end+1) = n('trailingColumnsTrimmedToOne', ...
                ['Keeping only neuron 4 -- one spike, in column 1 -- ' ...
                 'leaves a 1-by-1 activity. Trimming keeps at least one ' ...
                 'column, so a row of all zeros does not collapse to width 0.'], ...
                'testIncludeNames', ...
                ids, names, act, ...
                {'D'}, {}, [], [], {}, {}, [], [], ...
                'ok', {'id4'}, {'D'}, {41}, [1 1]);

            defs(end+1) = n('nothingKeptPreservesWidth', ...
                ['When nothing is kept, MATLAB''s isempty guard returns ' ...
                 'EARLY and the 0-by-Smax width survives -- so activity is ' ...
                 '0-by-3 rather than 0-by-1. Python''s port reproduces the ' ...
                 'asymmetry deliberately: a filter that kept nothing must ' ...
                 'not silently redefine the ensemble''s temporal width.'], ...
                '-- pins isempty asymmetry', ...
                ids, names, act, ...
                {}, {'A','B','C','D'}, [], [], {}, {}, [], [], ...
                'ok', {}, {}, {}, [0 3]);

            defs(end+1) = n('errorBadIndex', ...
                'IncludeIndex outside 1..N is an error, not a silent drop.', ...
                'testBadIndexErrors', ...
                ids, names, act, ...
                {}, {}, 5, [], {}, {}, [], [], ...
                'error', {}, {}, {}, []);

            defs(end+1) = n('errorBadKeepMask', ...
                ['A boolean Keep mask of the wrong length is an error, not ' ...
                 'a silent pad or truncate.'], ...
                'testBadKeepMaskErrors', ...
                ids, names, act, ...
                {}, {}, [], [], {}, {}, logical([1 0 1]), [], ...
                'error', {}, {}, {}, []);
        end % definitions

        % ----------------------------------------------------------------
        % running the battery
        % ----------------------------------------------------------------

        function rows = activityRendered(activity)
            % ACTIVITYRENDERED - one rendered sequence per activity row.
            %
            %   A 1xR cell (each entry a 1xC numeric row) becomes a 1xR cell
            %   of rendered strings. An empty cell stays empty, so the
            %   nothingKeptPreservesWidth case rounds-trips through JSON
            %   without becoming a single empty entry.
            if isempty(activity)
                rows = cell(1, 0);
                return;
            end
            rows = cell(1, numel(activity));
            for i = 1:numel(activity)
                rows{i} = ndi.symmetry.fun.cases.renderSequence(activity{i});
            end
        end % activityRendered

        function A = activityMatrix(activityRows, nNeurons)
            % ACTIVITYMATRIX - the N-by-Smax matrix filter is actually called with.
            %
            %   A 0-by-1 zero matrix when there are no rows; the filter is
            %   never called with this shape but a well-defined empty makes the
            %   fixture builder itself testable.
            if isempty(activityRows)
                A = zeros(nNeurons, 1);
                return;
            end
            A = vertcat(activityRows{:});
        end % activityMatrix

        function [ids, nameCells, act, shape, num] = describeOutput(E)
            % DESCRIBEOUTPUT - the compared parts of a filter result.
            ids = reshape(E.neuron_ids, 1, []);
            nameCells = reshape(E.neuron_names, 1, []);
            A = full(E.activity);
            [nr, nc] = size(A);
            shape = [nr nc];
            if nr == 0
                act = cell(1, 0);
            else
                act = cell(1, nr);
                for i = 1:nr
                    act{i} = ndi.symmetry.fun.cases.renderSequence(A(i, :));
                end
            end
            if isfield(E, 'info') && isstruct(E.info) && isfield(E.info, 'num_neurons')
                num = double(E.info.num_neurons);
            else
                num = 0;
            end
        end % describeOutput

        function results = runCases()
            % RUNCASES - run every case through ndi.fun.ensemble.filter and record it.
            %
            %   Errors are CAUGHT and recorded as status 'error' rather than
            %   thrown, for the reason given in FUN_CASES_SCHEMA.md section 6:
            %   a generator that dies on one case writes no artifact at all and
            %   costs the suite every other case's coverage.
            defs = ndi.symmetry.fun.ensembleFilterCases.definitions();

            results = cell(1, numel(defs));
            for i = 1:numel(defs)
                d = defs(i);

                rec = struct();
                rec.name = d.name;
                rec.note = d.note;
                rec.mirrors = d.mirrors;
                rec.neuronIds = reshape(d.neuronIds, 1, []);
                rec.neuronNames = reshape(d.neuronNames, 1, []);
                rec.activity = ndi.symmetry.fun.ensembleFilterCases.activityRendered(d.activity);
                rec.includeNames = reshape(d.includeNames, 1, []);
                rec.excludeNames = reshape(d.excludeNames, 1, []);
                rec.includeIndex = reshape(double(d.includeIndex), 1, []);
                rec.excludeIndex = reshape(double(d.excludeIndex), 1, []);
                rec.includeIds = reshape(d.includeIds, 1, []);
                rec.excludeIds = reshape(d.excludeIds, 1, []);
                rec.keepLogical = reshape(logical(d.keepLogical), 1, []);
                rec.keepIndex = reshape(double(d.keepIndex), 1, []);
                rec.status = 'ok';
                rec.identifier = '';
                rec.message = '';
                rec.neuronIdsOut = cell(1, 0);
                rec.neuronNamesOut = cell(1, 0);
                rec.activityOut = cell(1, 0);
                rec.shapeOut = zeros(1, 0);
                rec.numNeuronsOut = 0;

                E = struct();
                E.activity = ndi.symmetry.fun.ensembleFilterCases.activityMatrix( ...
                    d.activity, numel(d.neuronIds));
                E.neuron_ids = reshape(d.neuronIds, 1, []);
                E.neuron_names = reshape(d.neuronNames, 1, []);
                E.epoch = 'epoch_1';
                E.info = struct('num_neurons', numel(d.neuronIds), ...
                    'value_type', 'spiketimes');

                nvpairs = ndi.symmetry.fun.ensembleFilterCases.filterOptions(d);

                try
                    out = ndi.fun.ensemble.filter(E, nvpairs{:});
                    [rec.neuronIdsOut, rec.neuronNamesOut, rec.activityOut, ...
                        rec.shapeOut, rec.numNeuronsOut] = ...
                        ndi.symmetry.fun.ensembleFilterCases.describeOutput(out);
                catch ME
                    rec.status = 'error';
                    rec.identifier = ndi.symmetry.fun.cases.errorId(ME);
                    rec.message = ME.message;
                end

                results{i} = rec;
            end
        end % runCases

        function nvpairs = filterOptions(d)
            % FILTEROPTIONS - a 1x(2K) cell of Name,Value pairs for the filter.
            %
            %   Only the populated options are added, matching MATLAB's usual
            %   name/value convention. keepLogical and keepIndex both feed the
            %   single Keep argument; a definition sets at most one of them.
            nvpairs = {};
            if ~isempty(d.includeNames)
                nvpairs(end+1:end+2) = {'IncludeNames', reshape(d.includeNames, 1, [])};
            end
            if ~isempty(d.excludeNames)
                nvpairs(end+1:end+2) = {'ExcludeNames', reshape(d.excludeNames, 1, [])};
            end
            if ~isempty(d.includeIndex)
                nvpairs(end+1:end+2) = {'IncludeIndex', reshape(double(d.includeIndex), 1, [])};
            end
            if ~isempty(d.excludeIndex)
                nvpairs(end+1:end+2) = {'ExcludeIndex', reshape(double(d.excludeIndex), 1, [])};
            end
            if ~isempty(d.includeIds)
                nvpairs(end+1:end+2) = {'IncludeIds', reshape(d.includeIds, 1, [])};
            end
            if ~isempty(d.excludeIds)
                nvpairs(end+1:end+2) = {'ExcludeIds', reshape(d.excludeIds, 1, [])};
            end
            if ~isempty(d.keepLogical)
                nvpairs(end+1:end+2) = {'Keep', logical(reshape(d.keepLogical, 1, []))};
            elseif ~isempty(d.keepIndex)
                nvpairs(end+1:end+2) = {'Keep', double(reshape(d.keepIndex, 1, []))};
            end
        end % filterOptions

        % ----------------------------------------------------------------
        % comparison
        % ----------------------------------------------------------------

        function s = signature(c)
            % SIGNATURE - the compared part of one recorded case.
            %
            %   identifier and message are deliberately absent: MATLAB
            %   identifiers and Python exception names can never match, and
            %   pinning them would make this a translation table instead of a
            %   behaviour check. Only the FACT of an error is symmetric.
            shape = ndi.symmetry.fun.cases.asRow(c.shapeOut);
            shapeStr = strjoin(arrayfun(@(x) sprintf('%d', x), shape, ...
                'UniformOutput', false), 'x');
            s = strjoin({ ...
                ['status=' ndi.symmetry.fun.cases.asChar(c.status)], ...
                ['num=' sprintf('%d', double(c.numNeuronsOut))], ...
                ['ids=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.neuronIdsOut), '|')], ...
                ['names=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.neuronNamesOut), '|')], ...
                ['activity=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.activityOut), '|')], ...
                ['shape=' shapeStr]}, '; ');
        end % signature

        function s = inputSignature(c)
            % INPUTSIGNATURE - the inputs, so a green run cannot be comparing
            % two different batteries.
            keepLogicalArr = ndi.symmetry.fun.ensembleFilterCases.asBoolRow(c.keepLogical);
            keepLogicalStr = strjoin(arrayfun( ...
                @(b) ndi.symmetry.fun.cases.render(logical(b)), keepLogicalArr, ...
                'UniformOutput', false), '|');
            includeIdxStr = ndi.symmetry.fun.ensembleFilterCases.pipeInts(c.includeIndex);
            excludeIdxStr = ndi.symmetry.fun.ensembleFilterCases.pipeInts(c.excludeIndex);
            keepIdxStr = ndi.symmetry.fun.ensembleFilterCases.pipeInts(c.keepIndex);
            s = strjoin({ ...
                ['ids=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.neuronIds), '|')], ...
                ['names=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.neuronNames), '|')], ...
                ['activity=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.activity), '|')], ...
                ['includeNames=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.includeNames), '|')], ...
                ['excludeNames=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.excludeNames), '|')], ...
                ['includeIndex=' includeIdxStr], ...
                ['excludeIndex=' excludeIdxStr], ...
                ['includeIds=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.includeIds), '|')], ...
                ['excludeIds=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.excludeIds), '|')], ...
                ['keepLogical=' keepLogicalStr], ...
                ['keepIndex=' keepIdxStr]}, '; ');
        end % inputSignature

        function s = pipeInts(v)
            % PIPEINTS - '|'-joined integer tokens for a numeric row.
            r = ndi.symmetry.fun.cases.asRow(v);
            s = strjoin(arrayfun(@(x) sprintf('%d', x), r, ...
                'UniformOutput', false), '|');
        end % pipeInts

        function r = asBoolRow(v)
            % ASBOOLROW - normalize a decoded JSON bool array to a 1xN logical row.
            %
            %   jsondecode turns [] into 0x0 double and a single true into a
            %   scalar logical, so pass either through logical() and reshape.
            if isempty(v)
                r = false(1, 0);
            else
                r = reshape(logical(v), 1, []);
            end
        end % asBoolRow

        function [ok, detail] = checkExpected(d, rec)
            % CHECKEXPECTED - compare one recorded case against its expected output.
            %
            %   An error case pins only the FACT of the error; a success case
            %   pins the kept ids, names, activity (row by row) and the
            %   resulting shape.
            wantStatus = ndi.symmetry.fun.cases.asChar(d.expectedStatus);
            gotStatus = ndi.symmetry.fun.cases.asChar(rec.status);
            if ~strcmp(gotStatus, wantStatus)
                ok = false;
                detail = sprintf('expected status=%s, got status=%s (%s: %s)', ...
                    wantStatus, gotStatus, ...
                    ndi.symmetry.fun.cases.asChar(rec.identifier), ...
                    ndi.symmetry.fun.cases.asChar(rec.message));
                return;
            end
            if strcmp(wantStatus, 'error')
                ok = true;
                detail = 'error expected and observed';
                return;
            end

            wantAct = cell(1, numel(d.expectedActivity));
            for i = 1:numel(d.expectedActivity)
                wantAct{i} = ndi.symmetry.fun.cases.renderSequence(d.expectedActivity{i});
            end
            expShape = ndi.symmetry.fun.cases.asRow(d.expectedShape);
            wantShapeStr = strjoin(arrayfun(@(x) sprintf('%d', x), expShape, ...
                'UniformOutput', false), 'x');
            gotShape = ndi.symmetry.fun.cases.asRow(rec.shapeOut);
            gotShapeStr = strjoin(arrayfun(@(x) sprintf('%d', x), gotShape, ...
                'UniformOutput', false), 'x');

            want = strjoin({ ...
                ['ids=' strjoin(reshape(d.expectedIds, 1, []), '|')], ...
                ['names=' strjoin(reshape(d.expectedNames, 1, []), '|')], ...
                ['activity=' strjoin(wantAct, '|')], ...
                ['shape=' wantShapeStr]}, '; ');
            got = strjoin({ ...
                ['ids=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.neuronIdsOut), '|')], ...
                ['names=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.neuronNamesOut), '|')], ...
                ['activity=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.activityOut), '|')], ...
                ['shape=' gotShapeStr]}, '; ');
            ok = strcmp(want, got);
            detail = sprintf('expected [%s], got [%s]', want, got);
        end % checkExpected

    end % methods (Static)
end % classdef
