classdef parseTextCases
    % parseTextCases - shared, self-describing ndi.fun.parseText symmetry battery
    %
    %   MATLAB counterpart of tests/symmetry/fun/parse_text_cases.py. Both
    %   language ports run the SAME case list -- each case identified by an
    %   ASCII case NAME -- through their own real ndi.fun.parseText, then write
    %   the recorded outputs to
    %
    %     <tempdir>/NDI/symmetryTest/<matlabArtifacts|pythonArtifacts>/fun/
    %              parseText/testParseTextArtifacts/parseTextCases.json
    %
    %   The on-disk schema is documented in
    %   tests/+ndi/+symmetry/FUN_CASES_SCHEMA.md, section 9. READ THAT FILE
    %   before changing anything here.
    %
    %   This is a SEPARATE helper from ndi.symmetry.fun.cases rather than three
    %   more batteries inside it: cases.m is already 1238 lines. The canonical
    %   value grammar (render / renderSequence) and the artifact I/O
    %   (writeCases / loadCases / indexByName / asCellStr / errorId) are reused
    %   from ndi.symmetry.fun.cases, so the grammar stays single-sourced and
    %   only the battery is new.
    %
    %   WHAT THIS BATTERY IS FOR
    %   parseText turns a table of text plus a JSON file of regex rules into a
    %   MATLAB table, and almost all of its behaviour is IMPLICIT: whether a
    %   rule produces a logical column or a token column is decided by looking
    %   for '(' in the pattern text; whether a token becomes a number or a
    %   string is decided by looking for digit characters and then trying
    %   str2double; and the final column CLASS is decided by a flattening pass
    %   that can turn a column of empty strings into a logical column of false.
    %   None of that is written down anywhere, so a port has nothing to aim at
    %   except the source. Each case below pins one of those decisions, and
    %   columnTypes is compared precisely so the flattening pass cannot drift
    %   between the two languages while the values still happen to agree.
    %
    %   THE TWO TRAP CASES ARE THE POINT
    %   multipleGroupsFirstGroupWins and escapedParenTreatedAsToken pin
    %   behaviour that looks like a bug rather than a contract:
    %
    %     * A pattern with alternating capture groups -- the shipped
    %       XylidineDose rule is exactly this -- takes only the FIRST group.
    %       When the second alternative is the one that matched, the first
    %       group did not participate, so a row that plainly matched records
    %       the empty string. Python's re gives None where MATLAB gives '',
    %       so a port that does not map None to '' diverges here and nowhere
    %       else.
    %     * The '(' scan cannot tell an ESCAPED paren from a capture group, so
    %       a pattern like 'value\(\d+\)' is treated as a token rule even
    %       though it has no groups.
    %
    %   Both are recorded with expectationDeferred = true: they are what the
    %   source says, but the exact regexp return shape for a pattern with no
    %   participating groups is a source-read prediction, not a measurement.
    %   The artifact records whatever MATLAB really does and Python is compared
    %   against that, which is how the whatVaries battery settled its own two
    %   predictions -- one each way -- on first contact with a real runtime.
    %
    %   /!\ AUTHORED WITHOUT A MATLAB RUNTIME -- every expected value in this
    %   file is derived by reading src/ndi/+ndi/+fun/parseText.m branch by
    %   branch, not by executing MATLAB. VALIDATE BEFORE RELYING ON IT.
    %
    %   See also: ndi.symmetry.fun.cases,
    %     ndi.symmetry.makeArtifacts.fun.parseText,
    %     ndi.symmetry.readArtifacts.fun.parseText

    methods (Static)

        % ----------------------------------------------------------------
        % the battery
        % ----------------------------------------------------------------

        function c = newCase(name, note, clean, rules, inputRows, ...
                expNames, expTypes, expValues, deferred)
            % NEWCASE - one case definition, with the field order fixed.
            %
            %   RULES     Nx2 cellstr: {VariableName, StringFormat}
            %   INPUTROWS 1xR cell, each entry a 1xC cellstr (one text row)
            %   EXP*      the expected table, or {} when DEFERRED is true
            c = struct( ...
                'name', name, ...
                'note', note, ...
                'clean', logical(clean), ...
                'rules', {rules}, ...
                'inputRows', {inputRows}, ...
                'expectedNames', {expNames}, ...
                'expectedTypes', {expTypes}, ...
                'expectedValues', {expValues}, ...
                'expectationDeferred', logical(deferred));
        end % newCase

        function defs = definitions()
            % DEFINITIONS - the 18-case battery, as a 1xN struct array.
            n = @ndi.symmetry.fun.parseTextCases.newCase;
            defs = n('seed', '', true, cell(0,2), {}, {}, {}, {}, true);
            defs(1) = [];

            % --- logical (no capture group) rules ------------------------

            defs(end+1) = n('logicalMatch', ...
                ['A pattern whose only ''('' is followed by ''?'' is an inline ' ...
                 'flag, not a group, so hasToken is false and the rule yields ' ...
                 'a logical column.'], ...
                true, ...
                {'Heat', '(?i)heat'}, ...
                {{'sample_heat_1'}, {'sample_cold_2'}}, ...
                {'Heat'}, {'logical'}, {'[true, false]'}, false);

            defs(end+1) = n('logicalAllFalseCleaned', ...
                ['Clean removes every column that is all false. Both rules miss ' ...
                 'every row, so the result has NO columns at all.'], ...
                true, ...
                {'Heat', '(?i)heat'; 'Marker', 'zzz'}, ...
                {{'cold_1'}, {'cold_2'}}, ...
                cell(1,0), cell(1,0), cell(1,0), false);

            defs(end+1) = n('cleanFalseKeepsAllFalse', ...
                ['The same rules and input as logicalAllFalseCleaned with ' ...
                 'Clean=false: the columns survive, which is what proves the ' ...
                 'previous case measured Clean and not a parse failure.'], ...
                false, ...
                {'Heat', '(?i)heat'; 'Marker', 'zzz'}, ...
                {{'cold_1'}, {'cold_2'}}, ...
                {'Heat', 'Marker'}, {'logical', 'logical'}, ...
                {'[false, false]', '[false, false]'}, false);

            defs(end+1) = n('nonCapturingGroupIsLogical', ...
                ['(?:...) is a non-capturing group; the ''('' is followed by ' ...
                 '''?'' so hasToken is false and this is a logical rule.'], ...
                true, ...
                {'Kind', '(?:alpha|beta)'}, ...
                {{'alpha run'}, {'gamma run'}}, ...
                {'Kind'}, {'logical'}, {'[true, false]'}, false);

            defs(end+1) = n('columnsJoinedWithSpace', ...
                ['Each row''s columns are joined with a single space before ' ...
                 'matching, so a pattern may span the join.'], ...
                true, ...
                {'Joined', 'data\sfile'}, ...
                {{'data', 'file'}, {'data', 'other'}}, ...
                {'Joined'}, {'logical'}, {'[true, false]'}, false);

            % --- token rules: the numeric conversion ---------------------

            defs(end+1) = n('tokenNumeric', ...
                'A token containing digits that str2double accepts becomes a double.', ...
                true, ...
                {'Trial', 'experiment(\d+)'}, ...
                {{'experiment12'}, {'experiment7'}}, ...
                {'Trial'}, {'double'}, {'[12, 7]'}, false);

            defs(end+1) = n('tokenUnderscoreDecimal', ...
                ['Underscore is rewritten to ''.'' before str2double, so ''3_5'' ' ...
                 'is 3.5. This is the only reason the rewrite exists.'], ...
                true, ...
                {'Hours', '(\d+([._]\d+)?)[_ ]*(?:hr|hour)'}, ...
                {{'3_5 hr'}, {'12 hour'}}, ...
                {'Hours'}, {'double'}, {'[3.5, 12]'}, false);

            defs(end+1) = n('tokenRomanNumeralString', ...
                'A token with no digit characters is stored as text, never parsed.', ...
                true, ...
                {'Repetition', 'Rep\s([IVXLCDM]+)'}, ...
                {{'Fig Rep IV a'}, {'Fig Rep II b'}}, ...
                {'Repetition'}, {'cell'}, {'[''IV'', ''II'']'}, false);

            defs(end+1) = n('tokenDigitBearingNotANumber', ...
                ['''1B'' has a digit, so str2double is tried; it returns NaN, ' ...
                 'so the TEXT is kept. The column is then mixed text/number ' ...
                 'and stays a cell -- the discriminating case for the ' ...
                 'flattening pass.'], ...
                true, ...
                {'Label', 'label_([A-Za-z0-9]+)'}, ...
                {{'label_1B'}, {'label_42'}}, ...
                {'Label'}, {'cell'}, {'[''1B'', 42]'}, false);

            % --- token rules: what a MISS records ------------------------

            defs(end+1) = n('tokenMissingWithDigitPattern', ...
                ['A miss records NaN when the pattern text contains ''\d'' -- ' ...
                 'a literal substring test on the pattern, not on the match.'], ...
                true, ...
                {'Trial', 'experiment(\d+)'}, ...
                {{'experiment12'}, {'nothing here'}}, ...
                {'Trial'}, {'double'}, {'[12, NaN]'}, false);

            defs(end+1) = n('tokenMissingWithoutDigitPattern', ...
                'A miss records the empty string when the pattern has no ''\d''.', ...
                true, ...
                {'Repetition', 'Rep\s([IVX]+)'}, ...
                {{'Rep IV'}, {'no rep marker'}}, ...
                {'Repetition'}, {'cell'}, {'[''IV'', '''']'}, false);

            defs(end+1) = n('allMissesBecomeLogicalFalse', ...
                ['THE SUBTLE ONE. isempty('''') is true, so a column of nothing ' ...
                 'but empty strings satisfies the all-logical-or-empty test, ' ...
                 'every entry is replaced by false, and a TEXT rule ends up as ' ...
                 'a LOGICAL column -- which Clean then removes.'], ...
                true, ...
                {'Repetition', 'Rep\s([IVX]+)'}, ...
                {{'nothing'}, {'still nothing'}}, ...
                cell(1,0), cell(1,0), cell(1,0), false);

            defs(end+1) = n('allMissesLogicalVisibleWithoutClean', ...
                ['The same rule and input as allMissesBecomeLogicalFalse with ' ...
                 'Clean=false, so the logical column is visible instead of ' ...
                 'removed. Without this case the previous one could not tell a ' ...
                 'dropped logical column from a dropped text column.'], ...
                false, ...
                {'Repetition', 'Rep\s([IVX]+)'}, ...
                {{'nothing'}, {'still nothing'}}, ...
                {'Repetition'}, {'logical'}, {'[false, false]'}, false);

            defs(end+1) = n('allMissesNaNCleaned', ...
                'A column of nothing but NaN is numeric, and Clean removes it.', ...
                true, ...
                {'Trial', 'experiment(\d+)'}, ...
                {{'nothing'}, {'still nothing'}}, ...
                cell(1,0), cell(1,0), cell(1,0), false);

            % --- several rules and rows together -------------------------

            defs(end+1) = n('multiRowMixedTypes', ...
                ['Three rules of three different resulting classes over three ' ...
                 'rows, to pin column ORDER as well as content.'], ...
                true, ...
                {'Heat', '(?i)heat'; 'Trial', 'exp(\d+)'; 'Rep', 'Rep\s([IVX]+)'}, ...
                {{'heat exp1 Rep II'}, {'cold exp2 Rep IV'}, {'heat exp10 no rep'}}, ...
                {'Heat', 'Trial', 'Rep'}, ...
                {'logical', 'double', 'cell'}, ...
                {'[true, false, true]', '[1, 2, 10]', '[''II'', ''IV'', '''']'}, false);

            defs(end+1) = n('unicodeToken', ...
                ['A non-ASCII token, to exercise the UTF-8 artifact path. Both ' ...
                 'characters are in the BMP, so this is not an astral case and ' ...
                 'MATLAB''s UTF-16 char has no surrogate pair to expand.'], ...
                true, ...
                {'Name', 'subject_([^_ ]+)'}, ...
                {{['subject_caf' char(233)]}, {['subject_na' char(239) 've']}}, ...
                {'Name'}, {'cell'}, ...
                {['[''caf' char(233) ''', ''na' char(239) 've'']']}, false);

            % --- the two traps, expectations deferred --------------------

            defs(end+1) = n('multipleGroupsFirstGroupWins', ...
                ['TRAP. Only the FIRST capture group is read. Row 2 matches the ' ...
                 'second alternative, so group 1 did not participate and a row ' ...
                 'that plainly matched records the empty string. The shipped ' ...
                 'XylidineDose rule in +setup/+conv/+babu/textParser.json has ' ...
                 'exactly this shape. Python''s re gives None where MATLAB ' ...
                 'gives '''', so a port must map None to '''' or diverge here.'], ...
                true, ...
                {'Dose', '(\d+)MM|(\d+)\s+mM'}, ...
                {{'5MM'}, {'7 mM'}}, ...
                cell(1,0), cell(1,0), cell(1,0), true);

            defs(end+1) = n('escapedParenTreatedAsToken', ...
                ['TRAP. The ''('' scan cannot tell an escaped paren from a ' ...
                 'capture group, so this is treated as a token rule even ' ...
                 'though it has no groups. What regexp returns for ' ...
                 '''tokens'',''once'' on a group-less pattern decides whether ' ...
                 'the rows record NaN or something else, and that is a ' ...
                 'source-read prediction -- hence deferred.'], ...
                false, ...
                {'Paren', 'value\(\d+\)'}, ...
                {{'value(5)'}, {'value(9)'}}, ...
                cell(1,0), cell(1,0), cell(1,0), true);
        end % definitions

        % ----------------------------------------------------------------
        % running the battery
        % ----------------------------------------------------------------

        function s = rulesJson(rules)
            % RULESJSON - the parser file text for an Nx2 {name, pattern} cellstr.
            %
            %   Encoded from a CELL of scalar structs, never from a struct
            %   array: jsonencode collapses a 1x1 struct array to a bare JSON
            %   object, and a one-rule case would then be handed to Python as
            %   an object where every other case is an array.
            nRules = size(rules, 1);
            items = cell(1, nRules);
            for i = 1:nRules
                items{i} = struct('VariableName', rules{i,1}, ...
                    'StringFormat', rules{i,2});
            end
            s = jsonencode(items, 'PrettyPrint', true);
        end % rulesJson

        function s = rulesRendered(rules)
            % RULESRENDERED - the rules in the canonical grammar, for comparison.
            nRules = size(rules, 1);
            items = cell(1, nRules);
            for i = 1:nRules
                items{i} = struct('VariableName', rules{i,1}, ...
                    'StringFormat', rules{i,2});
            end
            s = ndi.symmetry.fun.cases.renderSequence(items);
        end % rulesRendered

        function c = inputRendered(inputRows)
            % INPUTRENDERED - one rendered sequence per text row.
            c = cell(1, numel(inputRows));
            for i = 1:numel(inputRows)
                c{i} = ndi.symmetry.fun.cases.renderSequence(inputRows{i});
            end
        end % inputRendered

        function m = inputMatrix(inputRows)
            % INPUTMATRIX - the RxC cell array parseText is actually called with.
            %
            %   ndi.setup.conv.babu.import passes table2cell(...) and cellstr
            %   file lists, so a cell array is the real-world input shape.
            if isempty(inputRows)
                m = cell(0, 0);
                return;
            end
            m = vertcat(inputRows{:});
        end % inputMatrix

        function results = runCases()
            % RUNCASES - run every case through ndi.fun.parseText and record it.
            %
            %   Errors are CAUGHT and recorded as status 'error' rather than
            %   thrown, for the reason given in FUN_CASES_SCHEMA.md section 6:
            %   a generator that dies on one case writes no artifact at all and
            %   costs the suite every other case's coverage.
            defs = ndi.symmetry.fun.parseTextCases.definitions();

            ruleDir = fullfile(tempdir(), 'NDI', 'symmetryTest', 'parseTextRules');
            if isfolder(ruleDir)
                rmdir(ruleDir, 's');
            end
            mkdir(ruleDir);
            cleaner = onCleanup(@() rmdir(ruleDir, 's')); %#ok<NASGU>

            results = cell(1, numel(defs));
            for i = 1:numel(defs)
                d = defs(i);

                rec = struct();
                rec.name = d.name;
                rec.note = d.note;
                rec.clean = d.clean;
                rec.rulesRendered = ndi.symmetry.fun.parseTextCases.rulesRendered(d.rules);
                rec.inputRendered = ndi.symmetry.fun.parseTextCases.inputRendered(d.inputRows);
                rec.status = 'ok';
                rec.identifier = '';
                rec.message = '';
                rec.columnNames = cell(1, 0);
                rec.columnTypes = cell(1, 0);
                rec.columnValues = cell(1, 0);
                rec.rowCount = 0;

                parserFile = fullfile(ruleDir, [d.name '.json']);
                fid = fopen(parserFile, 'w');
                if fid < 0
                    rec.status = 'error';
                    rec.identifier = 'ndi:symmetry:fun:parseTextCases:cannotWriteRules';
                    rec.message = ['Could not write ' parserFile];
                    results{i} = rec;
                    continue;
                end
                jsonStr = ndi.symmetry.fun.parseTextCases.rulesJson(d.rules);
                fwrite(fid, unicode2native(jsonStr, 'UTF-8'), 'uint8');
                fclose(fid);

                try
                    inputText = ndi.symmetry.fun.parseTextCases.inputMatrix(d.inputRows);
                    t = ndi.fun.parseText(inputText, parserFile, 'Clean', d.clean);
                    [rec.columnNames, rec.columnTypes, rec.columnValues] = ...
                        ndi.symmetry.fun.parseTextCases.describeTable(t);
                    rec.rowCount = height(t);
                catch ME
                    rec.status = 'error';
                    rec.identifier = ndi.symmetry.fun.cases.errorId(ME);
                    rec.message = ME.message;
                end

                results{i} = rec;
            end
        end % runCases

        function [names, types, values] = describeTable(t)
            % DESCRIBETABLE - column names, MATLAB classes, and rendered values.
            %
            %   The CLASS is compared as well as the values because the
            %   flattening pass at the end of parseText is where the two
            %   languages are most likely to drift: a column of empty strings
            %   becoming a logical column of false is invisible in the values
            %   alone once Clean has removed it.
            names = reshape(t.Properties.VariableNames, 1, []);
            types = cell(1, numel(names));
            values = cell(1, numel(names));
            for i = 1:numel(names)
                col = t.(names{i});
                types{i} = class(col);
                values{i} = ndi.symmetry.fun.cases.renderSequence(col);
            end
        end % describeTable

        % ----------------------------------------------------------------
        % comparison
        % ----------------------------------------------------------------

        function s = signature(c)
            % SIGNATURE - the compared part of one recorded case.
            %
            %   identifier and message are deliberately absent: MATLAB
            %   identifiers and Python exception names can never match, and
            %   pinning them would make this a translation table instead of a
            %   behaviour check. Only the FACT of an error is symmetric.
            s = strjoin({ ...
                ['status=' ndi.symmetry.fun.cases.asChar(c.status)], ...
                ['clean=' ndi.symmetry.fun.cases.render(logical(c.clean))], ...
                ['rows=' ndi.symmetry.fun.cases.render(double(c.rowCount))], ...
                ['names=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.columnNames), '|')], ...
                ['types=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.columnTypes), '|')], ...
                ['values=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.columnValues), '|')]}, '; ');
        end % signature

        function s = inputSignature(c)
            % INPUTSIGNATURE - the inputs, so a green run cannot be comparing
            % two different batteries.
            s = strjoin({ ...
                ['rules=' ndi.symmetry.fun.cases.asChar(c.rulesRendered)], ...
                ['input=' strjoin(ndi.symmetry.fun.cases.asCellStr(c.inputRendered), '|')]}, '; ');
        end % inputSignature

        function [ok, detail] = checkExpected(d, rec)
            % CHECKEXPECTED - compare one recorded case against its definition's
            % expected table. Returns ok=true for a deferred case.
            if d.expectationDeferred
                ok = true;
                detail = 'expectation deferred';
                return;
            end
            want = strjoin({ ...
                ['names=' strjoin(reshape(d.expectedNames, 1, []), '|')], ...
                ['types=' strjoin(reshape(d.expectedTypes, 1, []), '|')], ...
                ['values=' strjoin(reshape(d.expectedValues, 1, []), '|')]}, '; ');
            got = strjoin({ ...
                ['names=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.columnNames), '|')], ...
                ['types=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.columnTypes), '|')], ...
                ['values=' strjoin(ndi.symmetry.fun.cases.asCellStr(rec.columnValues), '|')]}, '; ');
            ok = strcmp(want, got) && strcmp(ndi.symmetry.fun.cases.asChar(rec.status), 'ok');
            detail = sprintf('expected [%s], got [%s] status=%s', ...
                want, got, ndi.symmetry.fun.cases.asChar(rec.status));
        end % checkExpected

    end % methods (Static)
end % classdef
