name: Deploy Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Start virtual display server
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'

      - name: Install mkdocs and mkdocs-material
        run: pip install mkdocs mkdocs-material

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@aa8bbc7b76daa63c5d456d1430cbd6cb5b626ab4 # v2
        with:
          release: 'latest'
          cache: true
          products: |
            Communications_Toolbox
            Statistics_and_Machine_Learning_Toolbox
            Signal_Processing_Toolbox

      - name: Install MatBox
        uses: ehennestad/matbox-actions/install-matbox@8fe220fbaec9e119ec5081eb917c8e016e275f1e # v1

      - name: Build Documentation (MATLAB)
        uses: matlab-actions/run-command@37b454c384483087929a3d652be474ba585a9659 # v2
        with:
          command: |
            mkdir('tools');
            copyfile('requirements.txt', fullfile('tools', 'requirements.txt'));
            matbox.installRequirements(fullfile(pwd, 'tools'));
            tools_path = fullfile(pwd, 'tools');
            if exist(tools_path, 'dir')
                addpath(genpath(tools_path));
            end
            addpath(genpath(fullfile(pwd, 'src')));
            addpath(genpath('MATLAB-AddOns'));
            ndi.docs.build();
            quit;

      - name: Prepare mkdocs files
        run: |
          mv src/ndi/docs/NDI-matlab/mkdocs.yml ./mkdocs.yml
          mv src/ndi/docs ./docs

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
