name: Call reusable test workflow

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - 'docs/reports/**'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-test-toolbox:
    name: Test
    uses: ehennestad/matbox/.github/workflows/reusable_test_workflow.yml@add-reusable-test-workflow
    inputs:
      code_directory: '.' # home directory
      tools_directory: 'tools'
      matlab_release: 'latest'
    secrets:
      commit_email_address: ${{ secrets.COMMIT_EMAIL_ADDRESS }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
