name: Call reusable test workflow

on:
  # Triggers the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
      - 'docs/reports/**'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Run tests (MATLAB latest release)
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          cache: true

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@add-reusable-test-workflow

      - name: Check code and upload report
        uses: ehennestad/matbox/.github/actions/check-code@add-reusable-test-workflow
        with:
          code_directory: +ndi

      - name: Run tests
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            setenv("NDI_CLOUD_USERNAME", "${{ secrets.NDI_CLOUD_USERNAME }}")
            setenv("NDI_CLOUD_PASSWORD", "${{ secrets.NDI_CLOUD_PASSWORD }}")
            addpath(genpath( "tests" ));
            testToolbox()

      # Commit updated SVG badges for the issues and tests (if changed)
      - name: Commit SVG badges if updated
        if: always()
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "${{ secrets.COMMIT_EMAIL_ADDRESS }}"
          git fetch 

          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update code issues and tests badges"
            git push -f
          else
            echo "Nothing to commit"
          fi

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: docs/reports/codecoverage.xml
          
      # Publish test results
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "docs/reports/test-results.xml"
