name: Test NDI Cloud Api

on:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Run tests (MATLAB latest release)
    runs-on: ubuntu-latest
    steps:      
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          cache: true

      - name: Install MatBox
        uses: ehennestad/matbox/.github/actions/install-matbox@v0.9

      - name: Run tests
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            setenv("NDI_CLOUD_USERNAME", "${{ secrets.NDI_CLOUD_USERNAME }}")
            setenv("NDI_CLOUD_PASSWORD", "${{ secrets.NDI_CLOUD_PASSWORD }}")
            ndi.cloud.authenticate("InteractionEnabled", "off")
            addpath('.')
            addpath(genpath( "tests" ));
            testToolbox()

      - name: Restore MATLAB Path
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            restoredefaultpath()
            savepath()
