name: Test NDI Cloud Api

on:
  # Run once a day
  schedule:
    - cron: '0 0 * * *'
      
  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

  push:
    branches:
      - add-cloud-api-testing # todo: remove this branch when merged

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Test Cloud API (env - ${{ matrix.environment }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [prod, dev]
    steps:      
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          cache: true

      - name: Install MatBox
        uses: ehennestad/matbox-actions/install-matbox@v1

      - name: Run tests
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            setenv("NDI_CLOUD_USERNAME", "${{ secrets.NDI_CLOUD_USERNAME }}")
            setenv("NDI_CLOUD_PASSWORD", "${{ secrets.NDI_CLOUD_PASSWORD }}")
            setenv("GITHUB_TOKEN", "${{ github.token }}")
            setenv("CLOUD_API_ENVIRONMENT", "${{ matrix.environment }}")
            addpath(genpath( "src" ));
            addpath(genpath( "tests" ));
            addpath(genpath( "tools" ));
            ndi.cloud.authenticate("InteractionEnabled", "off")
            testCloudApi()

      # Publish test results
      - name: Publish test results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'docs/reports/test-results.xml'

      - name: Restore MATLAB Path
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: |
            restoredefaultpath()
            savepath()
