exportDir = fullfile(ndi.common.PathConstants.CommonFolder, 'daq_systems', 'angeluccilab');
if ~isfolder(exportDir); mkdir(exportDir); end

commonFileParameters = {'#.nev', '^stimData.mat$', '^epochprobemap.txt$'};

% Export "angelucci_blackrock5" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'angelucci_blackrock5';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.blackrock', ...
    'FileParameters', [commonFileParameters, ...
    {'#.ns5'}], ...
    'EpochProbeMapFileParameters', '^epochprobemap.txt$' );

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

% Export "angelucci_visstim" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'angelucci_visstim';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.setup.daq.reader.mfdaq.stimulus.angelucci_visstim', ...
    'MetadataReaderClass', 'ndi.setup.daq.metadatareader.AngelucciStims', ...
    'FileParameters', [commonFileParameters, ...
    {'#.ns4'}], ...
    'EpochProbeMapFileParameters', '^epochprobemap.txt$', ...
    'MetadataReaderFileParameters', 'stimData.mat' );

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))
