exportDir = fullfile(ndi.common.PathConstants.CommonFolder, 'daq_systems', 'dbkatzlab');
if ~isfolder(exportDir); mkdir(exportDir); end


% Export "narendra_intan" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'narendra_intan';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
    'DaqReaderClass', 'ndi.daq.reader.mfdaq.intan', ...
    'MetadataReaderClass', 'ndi.daq.metadatareader', ...
    'FileParameters', {'time.dat', ...
    'info.rhd', ...
    'epochprobemap.txt', ...
    'intraoral_canulae.tsv', ...
    'optical_fiber1.tsv', ...
    'optical_fiber2.tsv'}, ...
    'EpochProbeMapFileParameters', 'epochprobemap.txt', ...
    'MetadataReaderFileParameters', {'stimulus_metadata_intraoral_canulae.tsv', ...
    'stimulus_metadata_optical_fiber1.tsv', ...
    'stimulus_metadata_optical_fiber2.tsv'} );

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))
