exportDir = fullfile(ndi.common.PathConstants.CommonFolder, 'daq_systems', 'vhlab');
if ~isfolder(exportDir); mkdir(exportDir); end


% Export "vhintan" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhintan';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
                 'DaqReaderClass', 'ndi.daq.reader.mfdaq.intan', ...
             'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
                 'FileParameters', {'reference.txt', ...
                                    '.*\.rhd\>', ...
                                    'vhintan_channelgrouping.txt', ...
                                    'vhintan_intan2spike2time.txt'}, ...
    'EpochProbeMapFileParameters', 'vhintan_channelgrouping.txt', ...
            'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))


% Export "vhspike2" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhspike2';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
                 'DaqReaderClass', 'ndi.daq.reader.mfdaq.cedspike2', ...
             'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
                 'FileParameters', {'reference.txt', ...
                                    '.*\.smr\>', ...
                                    'vhspike2_channelgrouping.txt'}, ...
    'EpochProbeMapFileParameters', 'vhspike2_channelgrouping.txt', ...
            'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))

daqSystemConfig2 = ndi.setup.DaqSystemConfiguration.fromConfigFile(...
    fullfile(exportDir, [daqSystemName, '.json']));


% Export "vhvis_spike2" DAQ System
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
daqSystemName = 'vhvis_spike2';
daqSystemConfig = ndi.setup.DaqSystemConfiguration( daqSystemName, ...
                 'DaqReaderClass', 'ndi.setup.daq.reader.mfdaq.stimulus.vhlabvisspike2', ...
             'EpochProbeMapClass', 'ndi.setup.epoch.epochprobemap_daqsystem_vhlab', ...
            'MetadataReaderClass', 'ndi.daq.metadatareader.NewStimStims', ...
                 'FileParameters', {'reference.txt', ...
                                    'stimtimes.txt', ...
                                    'verticalblanking.txt', ...
                                    'stims.mat', ...
                                    'spike2data.smr'}, ...
    'EpochProbeMapFileParameters', 'stimtimes.txt', ...
   'MetadataReaderFileParameters', 'stims.mat', ...
            'HasEpochDirectories', true);

daqSystemConfig.export(fullfile(exportDir, [daqSystemName, '.json']))
